-- Módulo Assessoria (14/09/2026) — cliente com contrato de acompanhamento contínuo.
-- Aplicado via migration `assessoria_schema`.
--
-- POR QUE EXISTE: ela pediu inicialmente um item de menu "Assessoria" embaixo de
-- Extrajudiciais. Investigando, achei que "Assessoria" já existia parcialmente como 1 valor
-- solto no datalist `processos_adm.orgao` — um meio-artefato, não uma funcionalidade de
-- verdade. Ela mandou 2 gravações de tela do OneDrive mostrando a estrutura real: cada
-- cliente de assessoria (ex. "08 ITALIA PANIFICADORA", "12 JONNIS PREMIUM FOOD") tem uma
-- pasta própria com dezenas de subpastas criadas à medida que surge situação nova (ex.
-- "19 ADVERTÊNCIA VALDEMIRA", "APOSENTADORIA JONI"), sem taxonomia fixa — inclusive uma
-- pasta "PROCESSOS" pra quando algo vira processo de verdade, e "INFORMATIVOS SEMANAIS"/
-- "MODELO DE CONTRATO" na raiz.
--
-- Ela corrigiu o foco 2 vezes antes da versão final:
--   1. "Isso é mais para poder cuidar dos prazos da assessoria e todas as demandas que
--      precisam" — o centro da funcionalidade é rastrear prazo/demanda, não replicar pasta
--      (pasta/subpasta livre tipo OneDrive fica pra depois, adiada por ela mesma).
--   2. "Não, não na mesma tela precisa ser tudo na aba assessórias, não se misturar com o
--      resto" — os prazos de demanda de assessoria NÃO podem aparecer na tela de Prazos
--      existente nem nos alertas de lá.
--   3. Sobre o atalho de menu: "igual tem independente a parte processos e a parte
--      extrajudicial e Becker IA, então assessoria é outro independente dos outros" — grupo
--      de menu PRÓPRIO, não subitem de Extrajudiciais, não aba escondida na ficha do cliente.
--
-- DESENHO: 4 tabelas novas, tudo aditivo, nenhuma coluna existente muda.
--
-- CREATE TABLE public.assessorias (
--   id           bigint generated always as identity primary key,
--   cliente_id   bigint not null unique references clientes(id) on delete cascade,
--   status       text not null default 'Ativa',   -- Ativa | Suspensa | Encerrada (texto, não
--                                                  -- boolean — mesmo idioma de
--                                                  -- clientes.status/processos.situacao)
--   data_inicio  date,
--   valor_mensal numeric(12,2),
--   escopo       text,
--   link_pasta   text,      -- mesmo padrão de novos_negocios.link_pasta (link externo, não
--                            -- estrutura de pasta em si)
--   observacoes  text,
--   created_at   timestamptz not null default now()
-- );
-- 1 linha = a própria marcação de "cliente tem assessoria". `on delete cascade` é deliberado
-- e diferente do resto do sistema (que usa `SET NULL`) — é ficha-detalhe 1:1 do cliente, nada
-- sobra sem ele.
--
-- CREATE TABLE public.assessoria_informativos (
--   id            bigint generated always as identity primary key,
--   assessoria_id bigint not null references assessorias(id) on delete cascade,
--   data_envio    date not null,
--   enviado_por   text,
--   observacao    text,
--   created_at    timestamptz not null default now()
-- );
-- Log do informativo semanal (ela tem uma pasta "INFORMATIVOS SEMANAIS" real no OneDrive) —
-- histórico, não só um "última data", pra dar pra ver quando foi mandado da última vez.
--
-- CREATE TABLE public.assessoria_demandas (
--   id           bigint generated always as identity primary key,
--   cliente_id   bigint references clientes(id) on delete set null,   -- mesmo padrão de
--                                                                     -- processos/documentos
--   titulo       text not null,      -- ex. "Advertência Valdemira", "Aposentadoria Joni"
--   tipo         text,               -- datalist livre de sugestão, NÃO enum fixo — mesmo
--                                     -- espírito do pedido dela, sem taxonomia rígida
--   descricao    text,
--   responsavel  text,               -- via respNomes(), mesmo padrão de processos/atendimentos
--   status       text not null default 'Aberta',   -- Aberta | Em andamento | Concluída |
--                                                   -- Arquivada | Convertida em processo
--   processo_id  bigint references processos(id) on delete set null,   -- só preenchido se a
--                                                                       -- demanda virar
--                                                                       -- processo de verdade
--   created_at   timestamptz not null default now()
-- );
-- O CONCEITO CENTRAL: uma demanda solta, com ou sem CNJ. `cliente_id` não tem FK direto pra
-- `assessorias` (é por cliente, não por contrato) — a lista cruzada "Demandas & Prazos" busca
-- os dois separadamente e cruza no JS, porque o PostgREST não embeda relações sem FK.
--
-- CREATE TABLE public.assessoria_demanda_prazos (
--   id           bigint generated always as identity primary key,
--   demanda_id   bigint not null references assessoria_demandas(id) on delete cascade,
--   data         date not null,
--   descricao    text not null,
--   cumprido     boolean not null default false,
--   cumprido_em  timestamptz,
--   cumprido_por text,
--   created_at   timestamptz not null default now()
-- );
-- A PEÇA QUE ISOLA DE `prazos`: clone pequeno e deliberado só dos campos que a tela de
-- Assessoria precisa — sem `ato_chave`, nunca lido por `carregarPrazos`/`renderPrazosLista`/
-- `trt_gera_prazos`/dashboard. Prazo de demanda de assessoria JAMAIS aparece na tela de Prazos
-- nem nos alertas de lá — é a garantia da correção que ela pediu.
--
-- RLS: policy becker_staff_all (for all to authenticated using (true) with check (true)) nas
-- 4 tabelas — mesmo padrão de processos/clientes/processo_clientes/documentos (conferido via
-- pg_policies antes de aplicar, não assumido).
--
-- UI (site/index.html): grupo de menu "🧭 Assessoria" próprio (renderSidebarMenu, perto dos
-- outros grupoMenu), com 2 itens — "Clientes" (pAssessoriaClientes, lista clientes com
-- assessoria ativa) e "Demandas & Prazos" (pAssessoriaDemandas, lista TODAS as demandas de
-- todos os clientes de assessoria com seus prazos, ordenada por próximo prazo em aberto —
-- equivalente da tela de Prazos, isolado, nunca cruza com `prazos`/`renderPrazosLista`).
-- Clicar num cliente abre `abrirAssessoriaCliente(id)` — página própria (não uma 8ª aba de
-- `abrirCliente`), com contrato/informativo/demandas + os documentos do cliente
-- (reaproveitando `carregarDocsCliente`, sem tabela nem upload novo). Botão
-- "⚖️ Transformar em Processo" numa demanda reaproveita `formProcesso()`/o mesmo fluxo de
-- validação de `novoProcesso()`, sem reinventar.
--
-- ACHADO LATERAL, corrigido na mesma PR: `carregarDocsCliente` fazia `order=criado_em.desc`
-- na query REST crua, mas a coluna real da tabela `documentos` é `created_at` — bug
-- pré-existente (não relacionado a Assessoria), a ordenação vinha sendo ignorada pelo
-- PostgREST desde sempre. Corrigido `criado_em`→`created_at`, e a função ganhou um 2º
-- parâmetro opcional `elId` pra poder renderizar tanto na aba Documentos da ficha quanto na
-- página de Assessoria.
--
-- ACHADO DURANTE TESTE (antes de publicar): a primeira versão de `buscarAssessoriaClientes`
-- tentava um embed do PostgREST `assessorias→assessoria_demandas` pra contar demandas em
-- aberto por cliente — mas não existe FK direto entre as duas tabelas (só via cliente_id),
-- então o embed teria falhado em produção. Corrigido pra 2 queries separadas cruzadas em JS
-- antes de considerar pronto; conferido depois via `pg_constraint` que todos os embeds
-- usados no código batem com FK real (nenhuma ambiguidade).
--
-- ADIADO PRA DEPOIS (ela mesma despriorizou frente aos prazos/demandas): pasta/subpasta livre
-- tipo OneDrive. Desenho já pensado, não implementado: tabela `pastas` (árvore
-- auto-referenciada por `pasta_pai_id`, `on delete cascade` — diferente de
-- `processos.processo_pai_id`, que é `no action`) + `documentos.pasta_id` nullable
-- (NULL = arquivo solto na raiz do cliente, igual o comportamento real do OneDrive).
--
-- NÃO CONSTRUÍDO (fora de escopo, evitar over-building sem pedido): alerta/badge de prazo de
-- demanda de assessoria; coluna `uploaded_by` em `documentos`.

-- ============================================================================
-- Migration `assessoria_pastas_schema` (14/09/2026, mesma sessão) — pastas fixas por cliente
-- ============================================================================
-- POR QUE: a "pasta livre tipo OneDrive" (seção anterior) ficou adiada porque na hora parecia
-- ser uma árvore de nome arbitrário. Ela mandou um exemplo concreto (print + um contrato de
-- prestação de serviços de verdade em .docx) mostrando que, na prática, todo cliente de
-- assessoria tem a MESMA taxonomia fixa de 7 pastas — não é livre, é sempre esse conjunto:
--
--   📄 CONTRATO BECKER (Contrato de Prestação de Serviços, Aditivos Contratuais)
--   👥 DOCUMENTOS DE FUNCIONÁRIOS (1 subpasta por funcionário, cresce com o tempo)
--   🏢 DOCUMENTOS EMPRESARIAIS (Contratos, Notificações, Termos, Outros)
--   ✍️ DOCUMENTOS ELABORADOS (Pareceres, Notificações, Consultas, Outros)
--   🔎 AUDITORIA (Auditoria Trabalhista, Auditoria Cível, Relatórios/Pendências)
--   ⚖️ PROCESSOS JUDICIAIS
--   🏛️ PROCESSOS ADMINISTRATIVOS
--
-- As duas últimas ela foi explícita que NÃO são pasta de arquivo: "dentro de cada parte só vai
-- aparecer o que é realmente ou da panificadora ou do jhonis" — ou seja, puxar os processos que
-- JÁ existem cadastrados (tabelas `processos`/`processos_adm`), filtrados por `cliente_id`, sem
-- duplicar dado (mesmo raciocínio da remoção da aba Documentos redundante, seção anterior desta
-- sessão).
--
-- Funcionários: "cadastro formal, mas também tudo dentro daquela acessória específica daquele
-- comércio para não se perder" — nome/cargo/cpf viram um cadastro de verdade (não só uma pasta
-- com nome livre), sempre amarrado a um cliente.
--
-- Auditoria: "arquivos e criar pendência" — as duas coisas, não uma ou outra: arquivo (reaproveita
-- a mesma categoria de documento) E uma lista de pendência com status, no mesmo espírito das
-- Demandas já existentes.
--
-- DESENHO: aditivo de novo — 2 tabelas novas + 3 colunas novas em `documentos` (nenhuma coluna
-- existente muda, nenhuma pasta/aba antiga perde dado).
--
-- CREATE TABLE public.assessoria_funcionarios (
--   id         bigint generated always as identity primary key,
--   cliente_id bigint not null references clientes(id) on delete cascade,
--   nome       text not null,
--   cargo      text,
--   cpf        text,
--   created_at timestamptz not null default now()
-- );
-- `on delete cascade` (não `set null`) de propósito: é exatamente o "para não se perder" dela —
-- o funcionário só existe dentro daquele cliente de assessoria, mesmo espírito de `assessorias`.
--
-- CREATE TABLE public.assessoria_pendencias (
--   id            bigint generated always as identity primary key,
--   cliente_id    bigint not null references clientes(id) on delete cascade,
--   tipo          text,               -- datalist livre (Trabalhista/Cível/Geral), não enum
--   titulo        text not null,
--   descricao     text,
--   status        text not null default 'Pendente',   -- Pendente | Concluída
--   concluido_em  timestamptz,
--   concluido_por text,               -- carimbado do perfil, mesma disciplina de autoria de
--                                     -- cumprir()/marcarInformativoEnviado()
--   created_at    timestamptz not null default now()
-- );
--
-- ALTER TABLE public.documentos
--   ADD COLUMN categoria text,                          -- 'contrato_becker' | 'funcionario' |
--                                                        -- 'empresarial' | 'elaborado' |
--                                                        -- 'auditoria' — NULL para todo
--                                                        -- documento fora de Assessoria
--                                                        -- (comportamento antigo intocado)
--   ADD COLUMN subcategoria text,                        -- datalist livre por categoria
--                                                        -- (Contratos/Notificações/Termos/...)
--   ADD COLUMN assessoria_funcionario_id bigint
--     REFERENCES assessoria_funcionarios(id) ON DELETE SET NULL;   -- mesmo padrão de
--                                                                  -- cliente_id/processo_id em
--                                                                  -- documentos: apagar o
--                                                                  -- funcionário não apaga o
--                                                                  -- arquivo, só desvincula
--
-- RLS: policy becker_staff_all nas 2 tabelas novas, mesmo padrão de sempre (conferido via
-- pg_policies antes de aplicar — as 3 tabelas de referência, processos/clientes/assessorias,
-- têm a mesma policy byte-idêntica).
--
-- UI (site/index.html): `abrirAssessoriaCliente`/`carregarAssessoriaCliente` ganham 6 blocos
-- novos, todos reaproveitando `documentos`/o bucket `documentos-clientes` já existentes — nenhum
-- upload/storage novo:
--   - `carregarDocsCategoria(clienteId, categoria, elId)` — genérica, serve Contrato Becker,
--     Empresariais, Elaborados e os arquivos de Auditoria (só muda o valor de `categoria`).
--   - `carregarFuncionariosAssessoria` + `carregarDocsFuncionario` — CRUD de funcionário e, por
--     funcionário, upload filtrado por `assessoria_funcionario_id` (categoria='funcionario').
--   - `carregarAuditoriaAssessoria` — pendências (`assessoria_pendencias`, CRUD completo com
--     concluir/reabrir, mesmo padrão de `cumprirPrazoDemanda`/`reabrirPrazoDemanda`) + arquivos
--     via `carregarDocsCategoria(...,'auditoria',...)`.
--   - `carregarProcessosAssessoria` — só leitura, 2 queries diretas (`processos`/`processos_adm`
--     filtradas por `cliente_id`, sem embed entre tabelas novas — mesma cautela da seção
--     anterior contra embed sem FK real), clicando abre `abrirProcesso`/`editarProcessoAdm` já
--     existentes.
--
-- Testado direto no banco antes de publicar (cliente de teste): funcionário + documento
-- vinculado, documento de categoria solta, pendência criada e concluída, cascade de
-- `assessoria_funcionario_id` (ON DELETE SET NULL) confirmado ao excluir o funcionário — o
-- documento continua existindo, só perde o vínculo. Tudo limpo depois (0 linhas de teste).
--
-- BUG REAL achado só depois de publicar (15/09/2026), migration `fix_assessoria_grants_authenticated`:
-- o teste acima (e todo teste anterior desta sessão) foi feito via SQL direto, com a role
-- `postgres`/service role — que ignora GRANT e RLS igual. Na tela de verdade, logada como
-- usuária normal (role `authenticated`), a lista "Assessoria → Clientes" dava 403 e "Erro ao
-- carregar": a policy RLS `becker_staff_all` estava certa nas 4 tabelas (`assessorias`,
-- `assessoria_demandas`, `assessoria_demanda_prazos`, `assessoria_informativos`, criadas na
-- migration `assessoria_schema`) e nas 2 novas desta sessão (`assessoria_funcionarios`,
-- `assessoria_pendencias`) — mas faltava o GRANT básico (SELECT/INSERT/UPDATE/DELETE) pra role
-- `authenticated` em TODAS as 6, só tinham REFERENCES/TRIGGER/TRUNCATE (herdados do owner). RLS
-- só decide DENTRO de uma operação já autorizada por GRANT — sem o GRANT, o Postgres nem chega
-- a avaliar a policy. Ou seja: a Assessoria inteira nunca tinha funcionado de verdade pela tela,
-- desde a PR #59 original, e ninguém tinha notado porque todo teste até aqui usou service role.
-- Corrigido com `grant select, insert, update, delete on <tabela> to authenticated;` nas 6.
-- Lição registrada: testar direto no banco prova que o SCHEMA está certo, não que a TELA
-- consegue acessar — falta sempre conferir os grants (comparar com `clientes`/`processos`, que
-- já tinham) antes de considerar uma tabela nova pronta pra produção.
