-- ============================================================================
-- CUSTO DA API DO LEGAL MAIL — o incidente de R$ 461 e a tabela de preços
-- 09/09/2026. Ver também LICOES.md (regras 1 a 7).
-- ============================================================================
--
-- *** ANTES DE AGENDAR QUALQUER ROTINA QUE CHAME O LEGAL MAIL, LEIA ESTE ARQUIVO. ***
--
-- Fonte: painel da API + spec OpenAPI 3.1.1 "LegalMail Public API" v1.0.0, 70 endpoints,
-- enviados pela Luana em 09/09/2026 e conferidos linha por linha contra a fatura.

-- ---------------------------------------------------------------------------
-- 1. O INCIDENTE
-- ---------------------------------------------------------------------------
-- Cron `legalmail-reconcile-horario` (`20 * * * *`) chamava GET /api/v1/notices SEM janela,
-- puxando o acervo inteiro: 3.302 intimações / 50 por página = ~67 requisições de R$ 0,05
-- = ~R$ 3,35 por execução, 24 vezes por dia. 112 execuções.
--
--   fatura (9.474 requisições)          R$ 478,26
--     /api/v1/notices          9.362    R$ 461,40   <-- 96,5% de tudo
--     case-files/download/request   5    R$  15,26
--     lawsuit/detail               35    R$   1,60
--     o resto (72 chamadas)              R$   0,00
--
--   por dia: 02/09 R$5 · 03/09 R$12 · 04/09 R$19 · 05/09 R$94 · 06/09 R$88
--            07/09 R$96 · 08/09 R$102 · 09/09 R$61 (até desligar)
--
-- O salto está em 05/09, quando o cron horário começou. Nenhuma dessas 9.265 chamadas cobradas
-- falhou (todas HTTP 200) — não houve erro de cobrança, e NÃO há base para contestar.
--
-- CRÉDITOS: assinatura de R$ 550/mês que EXPIRA ao fim do ciclo (o extrato tem a linha
-- "Remoção de sobra da assinatura — créditos expirados ao fim do ciclo"). Não acumula. Então
-- o dano não foi caixa, foi ORÇAMENTO QUEIMADO: sobrou R$ 65,69 para os 8 dias finais do ciclo,
-- que era o dinheiro dos downloads de autos.

-- ---------------------------------------------------------------------------
-- 2. O QUE A DOCUMENTAÇÃO DELES JÁ DIZIA
-- ---------------------------------------------------------------------------
-- Na descrição do próprio GET /api/v1/notices:
--   "Serve como ALTERNATIVA AO WEBHOOK (...): uma rotina DIÁRIA consegue puxar tudo o que foi
--    capturado no dia filtrando por data_captura_inicio / data_captura_fim."
--   "Cobrado POR REQUISIÇÃO (R$ 0,05), e não por intimação retornada — uma página com 50 custa
--    o mesmo que uma com 1."
--   "Janela de isenção de 5 MINUTOS (menor que o padrão de 24h da API)."
--   "CONSEQUÊNCIA PRÁTICA: CONSULTAR EM LAÇO SAI CARO — a cada 5 minutos há nova cobrança, e
--    nada é entregue que o puxão diário não entregue."
-- Boas práticas, na introdução: "Prefira webhooks a polling — polling reincidente gera bloqueio
-- progressivo." / "Monitore o saldo com GET /api/v1/balance."
--
-- O parâmetro `data_captura_inicio` JÁ ESTAVA implementado no nosso código (variável `since`),
-- e o cron chamava sem ele.

-- ---------------------------------------------------------------------------
-- 3. LIMITE DE TAXA — e o bloqueio que eu mesmo causei consertando isto
-- ---------------------------------------------------------------------------
--   * 120 requisições/min, em janela DESLIZANTE de 60s ("esperar a virada do minuto não zera").
--   * 3 respostas 429 em 10 minutos = "prática de polling" -> TIMEOUT PROGRESSIVO no workspace.
--   * Cada 429 conta como violação individual; as três podem cair no mesmo minuto.
--   * Durante bloqueio, tudo responde 429 com header Retry-After. Sai sozinho; a próxima
--     punição reinicia em 10 minutos.
--
-- Em 09/09 eu rodei a validação do fechamento (87 chamadas) TRÊS VEZES em cinco minutos = 261
-- chamadas. A terceira volta deu 0 de 87. Grátis não é ilimitado.
--
-- PIOR QUE O BLOQUEIO: naquela rodada cega a função respondeu "VENCENDO_HOJE_AINDA_ABERTOS: 0".
-- Ela havia falhado em 87 de 87 consultas e ainda assim afirmou que não havia pendência. Por
-- isso `prazos-fechar` agora devolve COMPLETO:false e contagens NULL quando qualquer consulta
-- falha. *** RODADA INCOMPLETA NÃO REPORTA NÚMERO. ***

-- ---------------------------------------------------------------------------
-- 4. PREÇOS DOS ENDPOINTS QUE NÓS USAMOS (tabela oficial, 09/09/2026)
-- ---------------------------------------------------------------------------
--   GRÁTIS  GET  /api/v1/balance                       saldo; a doc chama de "ideal para
--                                                      monitoramento automatizado"
--   GRÁTIS  GET  /api/v1/pleading/notices-to-comply    intimações pendentes POR PROCESSO,
--                                                      com tipo_prazo aberto/fechado
--   GRÁTIS  GET  /api/v1/lawsuit/case-files            lista os autos (só conta)
--   GRÁTIS  GET  /api/v1/lawsuit/case-files/download/status
--   GRÁTIS  GET  /api/v1/lawsuit/all, /summary
--   R$0,05  GET  /api/v1/notices                       POR PÁGINA de até 50. Isenção de 5 min.
--   R$0,05  GET  /api/v1/lawsuit/detail                por processo
--   R$0,07  GET  /api/v1/lawsuit/search                por página
--   R$0,15  POST /api/v1/lawsuit/case-files/update
--   R$0,02  POST /api/v1/lawsuit/case-files/download/request   *** POR AUTO DO PROCESSO INTEIRO
--   R$0,02  GET  /api/v1/lawsuit/docket-entry/url             *** POR DOCUMENTO ESCOLHIDO
--   R$0,25  POST /api/v1/pleading/send        R$1,00  POST /api/v1/complaint/send
--
-- SEM SALDO A REQUISIÇÃO NÃO É EXECUTADA: resposta 402.
--
-- PERGUNTA ANTIGA, RESPONDIDA: "download/request aceita subconjunto de documentos?" NÃO —
-- ele cobra R$0,02 por auto do processo INTEIRO. Para poucas peças use docket-entry/url, que
-- cobra R$0,02 só pelo documento pedido. A URL devolvida vale 6 DIAS: a doc avisa "guarde a URL
-- enquanto válida — pedir de novo é cobrança nova por um link que você ainda tinha".
-- Conferido no extrato: "Download completo dos autos (107 autos) — R$ 2,14" = 107 x R$ 0,02.

-- ---------------------------------------------------------------------------
-- 5. POR QUE O FECHAMENTO AUTOMÁTICO NUNCA FECHOU NADA (112 execuções, cumpridos:0)
-- ---------------------------------------------------------------------------
-- A spec define `prazo_status`:
--     pendente  = ainda a cumprir
--     cumprido  = *** VINCULADA A UMA PETIÇÃO PROTOCOLADA ***
--     excedido  = prazo excedido ou dispensada manualmente
--
-- O escritório protocola no eProc/PJe, NÃO pelo Legal Mail. Logo nenhuma intimação vira
-- `cumprido` lá: as 3.302 ficam `pendente` para sempre, o balde nunca esvazia — e era esse
-- balde que a rotina relia de hora em hora. Não era bug de ninguém: era mecanismo esperando um
-- sinal que o escritório nunca manda.
--
-- SOLUÇÃO (grátis): GET /api/v1/pleading/notices-to-comply usa o status do PRÓPRIO TRIBUNAL.
-- Devolve por processo `intimacoes_prazo_fechado` e `intimacoes_prazo_aberto`, e o campo
-- `idintimacoes` CASA EXATAMENTE com prazos.legalmail_id / publicacoes.legalmail_id
-- (conferido 6 a 6). Medido em 87 processos: 87 HTTP 200, R$ 0,00, 123 prazos avaliados,
-- 85 confirmados ABERTOS, 0 a fechar, 38 não listados.
-- Implementado na edge function `prazos-fechar`, cron `prazos_fechar_1730` (20:30 UTC = 17:30
-- BRT), com log em `prazo_fechamento_log`.
--
-- ATENÇÃO à nota antiga de db/legalmail_webhook.sql: ela dizia que notices-to-comply "veio
-- vazio". Foi testado num processo do TRT (que o Legal Mail não gerencia) e generalizado.
-- Nos processos do eProc responde com dados. Um caso não vira regra.

-- ---------------------------------------------------------------------------
-- 6. ESTADO DOS CRONS PAGOS
-- ---------------------------------------------------------------------------
--   legalmail-reconcile-horario   DESLIGADO (active=false) em 09/09  <-- causou os R$ 461
--                                 NÃO RELIGAR: o diário abaixo faz o mesmo trabalho. Se alguém
--                                 religar por engano hoje custa ~R$ 0,20/hora (a janela virou
--                                 padrão no código), não mais R$ 3,35/hora — mas continua sem
--                                 servir para nada.
--   legalmail_reconcile_diario    LIGADO em 10/09, `30 10 * * *` (07:30 BRT), URL com `?dias=3`
--                                 jobid 3. É a ÚNICA rotina que cria prazo de tribunal
--                                 não-trabalhista (ver seção 7). ~4 páginas = R$ 0,20/dia.
--
-- POR QUE RELIGAR (10/09) — ver seção 7. Resumo: com os dois desligados, TJSC/TJSP/TJPR/TRF-4/
-- STJ pararam de gerar prazo, porque o DJEN do CNJ não traz "Data final" em nenhuma linha.
--
-- Conserto do código, na mesma data (whatsapp-bot/edge-function-legalmail-reconcile.ts):
--   * `pendente` passou a respeitar a janela — era `null` cravado, e era isso que gastava;
--   * janela virou o PADRÃO (`?tudo=1` para desligar), com DIAS_PADRAO=3;
--   * TETO_PAGINAS=30 por rodada (R$ 1,50) — laço com defeito não vira mais fatura;
--   * aborta no primeiro 429 (Retry-After) e no 402 (sem saldo);
--   * a resposta devolve `paginas_cobradas` e `custo_estimado_brl`, então o gasto fica no log
--     de `net._http_response` sem depender do painel deles;
--   * cumprido/excedido saíram do plano padrão (`?fechados=1` religa): davam `cumpridos: 0`
--     em 112 execuções, e quem fecha prazo é o `prazos_fechar_1730`, de graça.
--
-- MEDIDO na primeira chamada consertada (10/09, ?dias=1&debug=1):
--   total 94 na janela · 2 páginas · R$ 0,10 · 94 publicações · 30 prazos criados/atualizados,
--   dos quais 18 PRAZOS NOVOS (16/09 a 01/10) que não estavam no sistema. Nenhum vencendo
--   hoje ou amanhã — o buraco de 16 h não custou prazo, por sorte.
--
-- Crons ativos e o custo de cada um:
--   prazos_fechar_1730     20:30  notices-to-comply + balance      R$ 0,00
--   djen_fire_diario       10:00  API Comunica do CNJ              R$ 0,00
--   djen_process_diario    10:06  SQL                              R$ 0,00
--   polo_diario            10:12  SQL                              R$ 0,00
--   trt_prazos_diario      10:20  SQL                              R$ 0,00
--   prazos_auditoria_mensal 11:00 dia 1  DataJud/CNJ               R$ 0,00
--   infinitum_sync_horario  :15   API do Infinitum (não Legal Mail) R$ 0,00

-- ---------------------------------------------------------------------------
-- 7. O DJEN NÃO SUBSTITUI O `notices` — medido em 10/09/2026
-- ---------------------------------------------------------------------------
-- Pergunta que originou a medição: "os prazos de hoje e de amanhã de todos os tribunais já
-- estão no sistema?"
--
-- Só existem DOIS caminhos que criam prazo:
--   lm_upsert_prazo_por_texto  exige "Data final" no texto   -> qualquer tribunal
--   trt_gera_prazos            tribunal ~ '^(TRT|TST)'       -> só trabalhista
--
-- `publicacoes` entre 01/08 e 10/09, por tipo:
--
--   tipo                                    linhas   com "Data final"   via DJEN   via LegalMail
--   Intimação por sistema (eProc)              757              265            0            757
--   DJEN/PJe + Diário Nacional + Intimação   1.199                0        1.195              4
--   Publicação                                 564                0            0            564
--
-- 0 de 757. A intimação eletrônica do eProc — a única que carrega a data-limite oficial do
-- tribunal — NÃO aparece no DJEN, nunca. Ela só chega pelo `notices` (pago).
--
-- Prova pelo efeito, no dia em que os dois crons estavam desligados (10/09 até 11h):
--   60 publicações novas (31 TJSC, 3 TJPR, 1 STJ, 25 trabalhistas), 0 com "Data final";
--   3 prazos criados, TODOS com fonte='DJEN/calculado' (caminho do TRT). Zero para TJSC.
--
-- CONCLUSÃO: o `notices` diário com janela não é luxo, é o alimentador de 490 processos ativos
-- do TJSC mais TJSP, TJPR, TRF-4 e STJ. R$ 0,20/dia. Cortar isso é cortar a entrada de prazo.
--
-- Conferência do acervo já existente (mesma data): TODAS as intimações com "Data final" oficial
-- de 10/09 ou 11/09 já tinham prazo — 19 de 19, 0 sem prazo (TJSC 7, TJSP 10, TRF-4 2). E o
-- dry-run `trt_gera_prazos('2026-08-25','2026-09-10',false)` voltou vazio. Ou seja: o que já
-- havia chegado estava completo; o problema era só a entrada NOVA.

-- ---------------------------------------------------------------------------
-- 8. O LEGAL MAIL NAO AVISA QUANDO O ESCRITORIO PETICIONA -- medido em 10/09/2026
-- ---------------------------------------------------------------------------
-- Pergunta dela: "agora vai conseguir identificar quando nos peticionamos e fechou o prazo?"
-- Resposta medida: NAO, nao de forma confiavel.
--
-- Gabarito 1 -- os 4 prazos de 09/09 que ela AFIRMA ter cumprido (5569, 5571, 5665, 5679):
--   repuxados hoje com janela de 30 dias (1.131 intimacoes, 23 paginas, R$ 1,15), e o teor
--   fresco do Legal Mail continua dizendo "Status do prazo: Prazo aberto" nos QUATRO.
-- Gabarito 2 -- os 43 prazos que o escritorio encerrou em bloco a mao:
--   as intimacoes deles NAO TRAZEM o campo "Status do prazo" nenhum. 43 de 43.
-- Contraexemplo -- prazo 5688: texto "Prazo fechado", Data final 24/09 (futura), fechado em
--   09/09 18:58 por lm_reconcile. Existe, mas e 1 caso, nao regra.
--
-- E o "fechamento automatico" que parecia funcionar e OUTRA COISA. Em
-- public.lm_upsert_prazo_por_texto:
--     cumpr := (dfinal < current_date);
--     ... status = case when cumpr then 'cumprido' else 'pendente' end, cumprido = cumpr
-- Marca "cumprido" SO PORQUE A DATA PASSOU. Classificacao dos 571 prazos fechados:
--   554  fechados so por data, sem prova nenhuma
--     6  texto do Legal Mail diz "Prazo fechado" (prova)
--     1  rotina estampou cumprido_por (prova)
--    10  outros
-- Isso e o oposto de controle de prazo: prazo PERDIDO sai da lista de pendencias com cara de
-- feito, e o sistema nao distingue cumprido de perdido.
--
-- Decisao dela: os 554 antigos FICAM como estao; conserto so daqui para frente.
--
-- O `pleading/notices-to-comply` (gratis) tambem nao resolveu: 95 processos, 132 prazos, todos
-- HTTP 200, rodada completa, e `a_fechar_detectados: 0`. Nunca um prazo em
-- `intimacoes_prazo_fechado`. Sobraram 38 "nao listados", e a hipotese a testar e que
-- ausencia da lista = fechado -- ainda NAO confirmada.
--
-- Cobertura da janela do /notices, medida nos 128 prazos abertos com intimacao (o mais antigo
-- tem 24 dias, mediana 13):
--   dias=3 -> 16 de 128 (12%)   dias=7 -> 31   dias=15 -> 76   dias=30 -> 128
-- A janela de 3 dias que ficou no cron em 09/09 deixava 88% dos prazos sem chance de fechar.
-- `data_captura_inicio` filtra pela data de CAPTURA, que nunca muda -- entao janela estreita
-- nao e otimizacao, e cegueira permanente para intimacao antiga.

-- ---------------------------------------------------------------------------
-- 9. O TESTE DO GABARITO -- o que significa um prazo nao aparecer na lista
-- Rodado em 10/09/2026, `?commit=0&gabarito=...`, custo R$ 0,00, nada gravado.
-- ---------------------------------------------------------------------------
-- Regra que a Luana deu: "nao aparece prazo em aberto no tribunal, sinal que fechamos".
-- Testada com 7 prazos de resposta conhecida (fechados COM prova: o teor do Legal Mail diz
-- "Prazo fechado"). Rodada completa: 94 processos, 94 HTTP 200, 0 erro.
--
--   prazo   vence        tribunal respondeu   esperado
--   5425    2026-07-29   FECHADO              nao_listado   <- nao bateu
--   5429    2026-07-29   FECHADO              nao_listado   <- nao bateu
--   5435    2026-08-07   FECHADO              nao_listado   <- nao bateu
--   5440    2026-07-21   nao_listado          nao_listado   ok
--   5441    2026-07-21   nao_listado          nao_listado   ok
--   5474    2026-08-24   nao_listado          nao_listado   ok
--   5688    2026-09-24   nao_listado          nao_listado   ok
--
-- ACHADO 1 -- `intimacoes_prazo_fechado` FUNCIONA. Minha expectativa estava errada, nao o
-- endpoint: 3 dos 7 vieram declarados FECHADO. O motivo de `a_fechar_detectados: 0` em todas
-- as rodadas anteriores e banal -- a consulta busca `cumprido=eq.false`, e os prazos abertos
-- estao genuinamente abertos. Nunca houve nada fechado para o endpoint achar.
--
-- ACHADO 2 -- "nao listado" NAO significa fechado. Dos 9 prazos que vencem hoje, 6 vieram
-- "nao listado", e 5 deles sao do TRT:
--   TJSC  5572, 5575, 5638  -> "aberto" (o tribunal confirma pendente)
--   TJSC  5639              -> "nao listado"  (e o duplicado da AGRO LAVOURA, mesmo processo
--                                              do 5638, que veio "aberto")
--   TRT   5714,5730,5736,5763,5773 -> "nao listado"
-- O eProc do TJSC nao conhece processo trabalhista. Ali "nao listado" quer dizer FORA DO
-- ESCOPO, nao "fechamos". Aplicar a regra da ausencia fecharia os 5 prazos do TRT de hoje
-- INDEVIDAMENTE. Por isso a regra, como estava enunciada, nao pode ser automatizada.
--
-- CONSEQUENCIA DE DESENHO: confiar no FECHADO declarado (funciona, e a rotina ja le) e
-- CLASSIFICAR a ausencia -- "fora do alcance" quando o processo nao e coberto pelo endpoint --
-- em vez de tratar ausencia como pendencia (o que faz hoje) ou como fechamento.

-- ---------------------------------------------------------------------------
-- 10. QUANDO o tribunal fecha o expediente -- nao e no protocolo
-- ---------------------------------------------------------------------------
-- Prazo 5688, CNJ 5031202-56.2026.8.24.0000, o unico fechado por rotina com prova. O teor:
--   "Status:FECHADO (105 - CIENCIA, COM RENUNCIA AO PRAZO)"
-- O numero entre parenteses e o ID DO EVENTO, nao codigo de motivo -- eu li errado primeiro.
-- Motivos existentes em TODA a base (9 intimacoes de ~11.000):
--   CIENCIA, COM RENUNCIA AO PRAZO ......... 8
--   Juntada de certidao - encerrado prazo ... 1
-- NENHUM diz "peticao protocolada".
--
-- O print do eProc que a Luana mandou fecha o raciocinio: o MESMO ato gera uma intimacao POR
-- DESTINATARIO. Evento 84 -> Cibele Becker Friedrichsen -> Status FECHADO (renuncia).
-- Evento 83 -> mesmo ato, outro advogado (rafael.azanha) -> Status ABERTO. A nossa fechou, a
-- dele nao, e o prazo segue visivel no eProc.
--
-- CONCLUSAO para a pergunta dela ("vai conseguir identificar quando nos peticionamos?"):
-- o sistema detecta o fechamento QUANDO O TRIBUNAL FECHA O EXPEDIENTE -- na ciencia/renuncia
-- ou na certidao do cartorio -- e NAO no instante do protocolo. Foi por isso que os 4 prazos
-- de 09/09 que ela protocolou continuavam com teor "Prazo aberto" na repuxada de hoje.
--
-- Terceiro sinal testado e descartado: `movimentacoes` esta CONGELADA em 15/08/2026 (0 linhas
-- nos ultimos 7 dias, 81 nos ultimos 30, de 44.544). Nenhum dos 4 processos tem movimentacao
-- depois da intimacao. A sincronia do DataJud nao esta rodando -- problema separado, anotado.

-- ---------------------------------------------------------------------------
-- 9. O TESTE DA REGRA DELA -- e o que o tribunal realmente diz (10/09/2026)
-- ---------------------------------------------------------------------------
-- Regra que ela propos: "nao aparece prazo em aberto no tribunal, sinal que fechamos".
-- Testada com gabarito de 7 prazos fechados COM prova, via `prazos-fechar?gabarito=&commit=0`,
-- custo R$ 0,00. Resultado 4/7 -- e os 3 que "erraram" foram a boa noticia:
--
--   prazo   vence      tribunal disse   eu esperava
--   5425    29/07      FECHADO          nao listado
--   5429    29/07      FECHADO          nao listado
--   5435    07/08      FECHADO          nao listado
--   5440    21/07      nao listado      nao listado   OK
--   5441    21/07      nao listado      nao listado   OK
--   5474    24/08      nao listado      nao listado   OK
--   5688    24/09      nao listado      nao listado   OK
--
-- CONCLUSAO 1: `intimacoes_prazo_fechado` FUNCIONA. Minha expectativa estava errada, nao o
-- endpoint. O `a_fechar_detectados: 0` de todas as rodadas anteriores tinha causa banal: a
-- consulta busca prazos abertos, e os abertos estavam genuinamente abertos. Nunca houve nada
-- fechado para achar.
--
-- CONCLUSAO 2: AUSENCIA NAO E FECHAMENTO. Dos 9 prazos que venciam em 10/09, o tribunal so
-- confirmou 3; os outros 6 nao foram mencionados e CINCO SAO DO TRT12, que o eProc do TJSC nao
-- conhece. Aplicar a regra da ausencia fecharia esses cinco indevidamente. A regra dela vale
-- para o caso que ela tinha em mente (TJSC), mas nao sobrevive ao TRT.
--
-- CONCLUSAO 3: QUANDO o tribunal fecha. O unico motivo de fechamento que existe na base e
-- "CIENCIA, COM RENUNCIA AO PRAZO" -- 8 de ~11.000 intimacoes; a nona diz "Juntada de certidao
-- - encerrado prazo". NENHUMA diz "peticao protocolada". Ou seja: o tribunal fecha o expediente
-- na ciencia/renuncia ou na certidao do cartorio, NAO no instante do protocolo. Foi por isso
-- que os 4 prazos que a Luana protocolou seguiam "Prazo aberto" no teor fresco.
--
-- CONCLUSAO 4: cada DESTINATARIO tem a sua intimacao do mesmo ato. No processo
-- 5031202-56.2026.8.24.0000 (print do eProc que ela mandou): evento 84, destinataria Cibele
-- Becker -> Status FECHADO (105 - CIENCIA, COM RENUNCIA AO PRAZO); evento 83, mesmo ato, outro
-- advogado -> Status ABERTO. Por isso o prazo aparece aberto no eProc mesmo resolvido do nosso
-- lado. E tambem por isso "aberto no tribunal" nao e o mesmo que "aberto para nos".
--
-- Correcao de leitura minha: o numero entre parenteses ("105 - CIENCIA...") NAO e codigo de
-- motivo, e o ID DO EVENTO -- varia (143, 89, 105, 138, 65, 98). O motivo e o texto depois do
-- traco, e existem so dois na base inteira.
--
-- OUTRO SINAL TESTADO E DESCARTADO: `movimentacoes` esta PARADA em 15/08/2026 -- zero
-- movimentacao nos ultimos 7 dias, 81 nos ultimos 30, de 44.544 no total. Nenhum dos 4
-- processos protocolados tem movimentacao depois da intimacao. A sincronia do DataJud nao esta
-- rodando; enquanto nao rodar, "apareceu movimentacao de peticao" nao serve de sinal.

-- ---------------------------------------------------------------------------
-- 10. O DESENHO QUE FICOU, E O DEFEITO QUE EU INTRODUZI CONSERTANDO
-- ---------------------------------------------------------------------------
-- `prazos-fechar` passou a responder em TRES grupos, cada um dizendo so o que se sabe:
--   FATAIS_SEM_CUMPRIR        tribunal DECLAROU aberto, e ja venceu ou vence hoje   -> 3
--   SEM_RESPOSTA_DO_TRIBUNAL  tribunal nao falou deste (com o tribunal de cada um)  -> 6
--   FORA_DA_ROTINA            a rotina nem consegue olhar                           -> 3
-- A SOMA TEM DE FECHAR com o total de prazos abertos do dia (12 em 10/09). Isso e o teste de
-- que ninguem sumiu: 3 + 6 + 3 = 12.
--
-- E foi exatamente esse teste que pegou um defeito MEU. Na primeira versao o filtro do
-- FORA_DA_ROTINA era
--     .filter((z) => !z.legalmail_id || !z.processos)
-- com um `select` que nem trazia `lm_idprocessos`. A soma dava 11, nao 12. O que faltava era o
-- prazo 5574 (DANIEL GONCALVES COSTA, TJSC, vencendo naquele dia): o processo 6698 existe e o
-- prazo tem intimacao, mas o processo esta sem `lm_idprocessos`. A consulta principal usa
-- `processos!inner` e o descarta; o filtro de resgate tambem. Ele sumia dos TRES grupos --
-- exatamente a omissao silenciosa que o grupo existia para impedir. Corrigido com
--     .filter((z) => !z.legalmail_id || !z.processos || !z.processos.lm_idprocessos)
-- e o `motivo` passou a distinguir os tres casos.
--
-- REGRA QUE FICA: relatorio de cobertura tem de FECHAR A SOMA com o universo. Contar so os
-- grupos "interessantes" esconde justamente o item que ninguem esta olhando.

-- ---------------------------------------------------------------------------
-- 11. O "cumprido" FALSO -- migration prazo_nao_fecha_por_data (10/09/2026)
-- ---------------------------------------------------------------------------
-- `lm_upsert_prazo_por_texto` fazia `cumpr := (dfinal < current_date)` e gravava
-- `cumprido = cumpr`. Prazo VENCIDO virava CUMPRIDO, sem ninguem ter protocolado nada.
-- Dos 571 prazos fechados: 554 assim, sem prova; 6 com "Prazo fechado" no texto; 1 com
-- `cumprido_por` estampado; 10 outros.
-- Agora data vencida produz `status='excedido'` com `cumprido=false`. `cumprido=true` tem UMA
-- origem: prova (Legal Mail declarando, notices-to-comply declarando, ou clique humano), e toda
-- escrita estampa `cumprido_em`/`cumprido_por`.
-- Os 554 antigos NAO foram tocados -- decisao dela: "so daqui pra frente". O passado fica
-- impreciso e nao ha como reconstruir; so o tribunal saberia.
