-- public.trt_gera_prazos(p_de, p_ate, p_commit) — cria o prazo trabalhista que o tribunal não
-- manda. (aplicado via migrations `trt_gera_prazos` e `trt_gera_prazos_fix_ambiguidade`)
--
-- POR QUE EXISTE: o diário do TRT nunca traz "Data final", e lm_upsert_prazo_por_texto() aborta
-- sem esse campo (`if dfinal is null then return 0`). Resultado: 3.245 intimações do TRT e 0
-- prazos. Ver db/pje_comunica_20260908.sql para o levantamento completo.
--
-- ESTE É O CAMINHO PRINCIPAL, e não um paliativo — reavaliado em 09/09/2026.
-- A vantagem decisiva dele não é técnica, é processual: o cálculo NÃO TOCA EM NADA no tribunal.
-- Não dá ciência, não abre comunicação, não deixa rastro, não antecipa contagem de prazo. Risco
-- processual zero.
-- A alternativa "oficial" (campo `prazo` do Domicílio Eletrônico) foi descartada justamente
-- porque consultá-la pode constituir ciência e iniciar o prazo — ver db/pje_comunica_20260908.sql.
-- Ou seja: mesmo se a credencial do CNJ aparecer amanhã, não é troca automática. Só se troca a
-- data calculada pela oficial se o CNJ confirmar por escrito que a consulta não dá ciência.
--
-- COMO CALCULA:
--   data_prazo = becker_dias_uteis(becker_dias_uteis(disponibilizacao, 1), 5)
--                (disponibilização + 1 dia útil de ciência + 5 dias úteis, sem feriado)
--   Conferido contra a tela "Meus Expedientes" do PJe: 6 de 6 exatas.
--
-- N = least(5, menor prazo DIRIGIDO no texto). O texto só ENCURTA, nunca alonga.
--
-- Como se chegou aqui (a primeira versão estava errada, corrigida em 09/09/2026):
--
-- Ponto de partida: N=5 fixo, porque 4 dos 6 atos do gabarito não contêm nem a palavra "prazo",
-- 5 dos 6 não citam número de dia nenhum, e todos tinham prazo real. Regra do tipo "só cria se o
-- texto falar de prazo" perderia 4 dos 6, incluindo 3 dos 4 que venciam em 10/09.
--
-- O erro que eu cometi: justifiquei o 5 fixo dizendo que 5 é o menor prazo comum, logo o erro
-- seria sempre "para antes", que é seguro. A Luana lembrou de um caso antigo (o sistema abria 15
-- e a intimação dizia 8) e pediu para conferir. A premissa era FALSA. Nos atos reais existe:
--     "diga o autor em 2 dias se insiste na prova oral requerida"                    (4 atos)
--     "Intimem-se as partes para que digam, em 48 horas, se têm interesse em ..."     (3 atos)
-- "O autor" e "as partes" incluem o nosso cliente. Prazo real de 2 dias, e o 5 dava data DEPOIS
-- da real — a direção que PERDE PRAZO. Um dos 71 prazos já gravados estava assim (id 5734,
-- mostrava 28/08 quando o certo era 25/08); foi corrigido à mão.
--
-- Como se acha sem gerar ruído: casar ORDEM DIRIGIDA + PRAZO, não número solto.
--     verbo (diga|digam|manifeste|informe|apresente|comprove|junte|cumpra|esclareça|indique)
--     + "em|no prazo de|dentro de" + N + (dias|horas)
-- Em 397 atos isso casa 10 vezes — 2 dias (x4), 5, 8, 10, 48 horas (x3) — e nenhum boilerplate.
-- Casar número solto pegava 44 atos, quase todos norma citada ou prazo de outra parte.
--
-- POR QUE SÓ ENCURTA:
--   * texto diz 2 dias ou 48 horas -> usa 2   (corrige o caso perigoso)
--   * texto diz 8 ou 10            -> mantém 5 (antecipa; a pessoa estende na conferência)
--   * texto não diz nada           -> 5        (o padrão validado 6/6 contra o PJe)
-- Alongar automaticamente é exatamente o erro do estimador antigo de "+15 dias úteis", removido
-- na v3 da reconciliação por isso mesmo (db/legalmail_webhook.sql, seção 6).
--
-- E NÃO converter "24/48/72 horas" às cegas: das 22 menções a horas, a maioria está ancorada
-- noutra data ("48 horas antes da sessão", "24 horas antes da audiência") ou é norma citada
-- (art. 880 da CLT). Encurtar tudo criaria urgência falsa, e fila que grita sem motivo deixa de
-- ser lida. Só vale dentro da ordem dirigida.
--
-- ARMADILHA DE IMPLEMENTAÇÃO, que me pegou: ao tornar o grupo do verbo NÃO-capturante, os índices
-- andam — m[1] é o número e m[2] a unidade. Eu havia usado m[2] e m[3], e a função ESTOURAVA
-- ('horas'::int) justamente ao encontrar a ordem dirigida. Não foi pego na primeira conferência
-- porque a janela testada não tinha nenhuma ordem dirigida: a subconsulta nunca era avaliada.
-- Teste que não exercita o caminho novo não é teste — conferir sempre em junho/julho, onde os
-- casos existem.
--
-- ESCOPO: lê de publicacoes_atos (NUNCA de publicacoes direto, senão volta a duplicar).
--   tribunal ~ '^(TRT|TST)'  -- regex, por causa das grafias duplas TRT-12/TRT12
--   sem 'data final' no texto  -- não invadir o caminho que já funciona nos outros tribunais
--   sem 'pauta de julgamento' nem 'ata de sessão'  -- não são expediente com prazo
--
-- IDEMPOTÊNCIA: coluna prazos.ato_chave (cnj|data|ID do ato) + índice único parcial
--   prazos_ato_chave_uk. Rodar duas vezes não duplica. Também pula se já existe prazo do mesmo
--   processo na mesma data-limite (evita bater com prazo vindo por outro caminho).
--
-- GRAVA: status='estimado', tipo='Prazo', fonte='DJEN/calculado', cumprido=false,
--   categoria via lm_categoria_prazo() (que já existia), alertar_dias=3.
--   Descrição: "CLIENTE · TRT-12 — ESTIMADO: disp. dd/mm +1+5 dias úteis [· texto cita N dias]".
--
-- ARMADILHA DE IMPLEMENTAÇÃO: o parâmetro OUT não pode se chamar `ato_chave` — colide com a
-- coluna dentro do `on conflict (ato_chave)` e o Postgres recusa por ambiguidade. Alias no
-- INSERT não resolve: o conflict_target do ON CONFLICT só aceita nome de coluna sem qualificação.
-- Por isso o OUT se chama `chave_do_ato`.
--
-- USO:
--   select * from trt_gera_prazos('2026-08-20','2026-09-08', false);  -- SIMULA, não grava
--   select * from trt_gera_prazos('2026-08-20','2026-09-08', true);   -- grava
--   -- desfazer:  delete from prazos where fonte='DJEN/calculado';
--
-- PRIMEIRA RODADA (08/09/2026): 71 prazos, 57 com processo vinculado, 14 sem.
--   37 em aberto, 34 já vencidos (28/08 a 04/09).
--   Os 34 vencidos foram MANTIDOS de propósito: prazo que expirou antes de o sistema saber dele
--   é justamente o caso de prazo possivelmente perdido, que é o que este trabalho existe para
--   revelar. Não são ruído — precisam ser conferidos um a um.
--   Nenhum outro status de prazo se moveu (conferido antes/depois): só estimado, +71.
--
-- FECHAMENTO AUTOMÁTICO (corrigido em 09/09/2026):
-- O prazo nasce com `legalmail_id` do aviso do Legal Mail que cobre o MESMO ato, porque
-- lm_reconcile() — quem fecha prazo quando o tribunal informa cumprido/excedido — casa por
-- legalmail_id e não por ato_chave. Os 71 primeiros nasceram sem esse vínculo e ficariam
-- abertos para sempre mesmo depois de cumpridos; foram ligados na mão e a função corrigida.
-- A view publicacoes_atos expõe `legalmail_id_do_ato` (qualquer cópia do grupo serve: o status
-- vem do tribunal e é igual para todas). O vínculo só é gravado se nenhum outro prazo já usar
-- aquele id, porque uq_prazos_legalmail é único.
--
-- LIMITE CONHECIDO, medido em 09/09/2026: para o TRT o Legal Mail NÃO reporta prazo_status.
-- Rodada completa de reconciliação (5.449 avisos) fechou 15 prazos de outros tribunais
-- (12 cumpridos, 3 excedidos) e ZERO dos 71 do TRT. É a mesma causa raiz: sem "Data final" o
-- Legal Mail nunca registrou prazo para o TRT, então não tem status para informar.
-- Quem fecha prazo trabalhista, então:
--   1. Export "Meus Expedientes" do PJe: o que NÃO está na lista já foi cumprido. Autoritativo
--      e grátis, mas manual.
--   2. Domicílio Eletrônico da PDPJ: tem os campos (ciente, dataCiente, emCurso, status), mas
--      DESCARTADO por decisão da Luana em 09/09/2026 — consultar lá pode constituir CIÊNCIA, e
--      ciência inicia o prazo. Automatizar a leitura queimaria a folga até a ciência tácita em
--      todo processo, todo dia. Além disso é a caixa do destinatário, e cadastro de pessoa
--      física é opcional, então provavelmente não cobre a carteira de reclamantes daqui.
--      Ver db/pje_comunica_20260908.sql para o raciocínio completo. NÃO LIGAR sem resposta
--      escrita do CNJ.
--   3. MNI-REST consultar-avisos-pendentes: DESCARTADO em 09/09/2026, depois de testar.
--      A ideia era boa (a lista de avisos pendentes é o inverso do que fechou, e o corpo do
--      pedido leva usuario/senha DO TRIBUNAL, não do CNJ), mas não se chega lá:
--        - via gateway da PDPJ: 401 com WWW-Authenticate: Bearer realm="Unknown" — o gateway
--          exige token OAuth2 do CNJ ANTES de olhar o usuario/senha do corpo. Mesmo bloqueio
--          do caminho 2, então não é alternativa a ele.
--        - em produção o mni-rest responde 500 "GENERAL" (o registro do Eureka que eu li é de
--          homologação; não parece publicado em produção).
--        - direto no tribunal (pje.trt12.jus.br/.../intercomunicacao): 403 do CloudFront em
--          TUDO, inclusive na home. É bloqueio de tráfego de datacenter, não da API: o
--          www.trt12.jus.br (outra infra) responde 200 normalmente. Ou seja, integração
--          servidor-a-servidor não alcança o PJe do TRT12 de forma alguma.
--      Não se tenta contornar o bloqueio deles.
--   4. DataJud (API pública do CNJ, api-publica.datajud.cnj.jus.br): a ideia certa — os
--      movimentos vêm com código da TPU, e "Petição" (código 85) juntada depois da
--      disponibilização é sinal forte de cumprimento. TESTADO em 09/09/2026 nos 32 vencidos
--      com CNJ, e NÃO SERVE PARA FECHAR NO PRAZO, por atraso da fonte:
--        - encontrados 26 de 32;
--        - TODOS os 26 com dataHoraUltimaAtualizacao = 2026-08-10 (uma carga só, mensal);
--        - o movimento mais recente de cada um é de julho ou antes;
--        - 0 de 26 têm qualquer movimento na data da intimação (20-28/08) ou depois;
--        - 0 de 26 têm Petição posterior à intimação.
--      O TRT12 manda para o DataJud em lote de ~30 dias. Prazo de 5 dias úteis não pode ser
--      confirmado por fonte que chega um mês depois. A API responde bem e SEM bloqueio
--      geográfico (funciona até de fora do Brasil), o problema é só a defasagem.
--      PARA QUE SERVE, ENTÃO: auditoria retrospectiva. Rodando um mês depois, o DataJud diz se
--      houve petição em cada prazo estimado — pega prazo realmente perdido e mede o acerto do
--      cálculo. Vale construir, mas como conferência mensal, não como fechamento.
--      A função datajud-enriquecer já existe e já consulta essa API (só usa classe/assunto e
--      descarta `movimentos`); o caminho para a auditoria é aproveitar ela.
--
-- NÃO usar "houve movimento posterior no processo" (qualquer publicação depois da data) para
-- fechar: em 09/09 isso valia para 10 dos
-- 39 vencidos, e é indício, não prova de cumprimento. Fechar prazo por indício é pior do que
-- deixar aberto.
--
-- AGENDADO em cron.job (nada disso rodava antes — ver db/djen_supabase_pgcron.sql):
--   trt_prazos_diario  '20 10 * * *'  select trt_gera_prazos(current_date-15, current_date, true)

-- ============================================================================
-- 10/09/2026 — AVISO DE DISTRIBUIÇÃO NÃO É PRAZO (migration trt_ignora_distribuicao)
-- ============================================================================
-- Origem: pergunta dela — "verificar também tudo o TST que estão vindo também certinho".
-- A coleta do TST estava certa. O defeito estava no que esta função faz com ela.
--
-- O ATO, na íntegra (263 caracteres, é tudo o que existe):
--   "Processo 0000007-12.2025.5.12.0016 distribuído para 3ª Turma - Gabinete da Ministra
--    Margareth Rodrigues Costa na data 05/09/2026. Para maiores informações, clique no
--    link a seguir: https://pje.tst.jus.br/..."
-- Não manda fazer nada. Não abre prazo. Mas a regra desta função é "todo ato sem Data final
-- vira prazo de 5 dias úteis", e a lista de exceções só tinha pauta e ata de sessão.
--
-- MEDIDO em 10/09/2026, no universo trabalhista inteiro (1.195 atos em publicacoes_atos):
--   atos que são puro aviso de distribuição ......... 174   (130 TRT + 44 TST)
--   deles, que já haviam virado prazo ................ 14   (6 ainda em aberto)
--   maior texto entre os 174 ......................... 304 caracteres
--   dos 174, quantos contêm QUALQUER palavra de ordem   0   (nem "prazo", nem "intime",
--                                                           nem verbo imperativo)
--
-- A REGRA (ancorada no início do texto, de propósito):
--   texto ~* '^\s*Processo\s+[0-9.\-]+\s+distribu(i|í)do para'
--   AND length(becker_html_texto(texto)) < 600
-- Só casa quando o ato INTEIRO é a linha de distribuição. A guarda de tamanho hoje não tira
-- nada (o maior tem 304); existe para o dia em que o tribunal juntar uma ordem depois da
-- distribuição — nesse dia o ato VOLTA a gerar prazo, em vez de sumir calado.
--
-- POR QUE NÃO FILTRAR POR `tipo`: dos 49 avisos de distribuição do TST, só 3 chegam como
-- 'Lista de distribuição'; os outros 46 chegam como 'DJEN/PJe', igual a um despacho.
-- `tipo` é o rótulo da FONTE de coleta, não do ato — o mesmo achado de db/publicacoes_atos.sql.
--
-- CONFERÊNCIA (dry-run 2025-07-01 → 2026-09-10):
--   TST ....... 61 candidatos ANTES  →  20 DEPOIS   (61 − 41; os outros 3 dos 44 já tinham prazo)
--   avisos de distribuição que sobraram no dry-run: 0
--   os 6 prazos falsos em aberto (5713, 5723, 5754, 5760, 5762, 5779) foram para
--     status='descartado', cumprido=true, cumprido_por='descartado/aviso-de-distribuicao'
--   auditoria "cumprido and cumprido_por is null": 570 antes, 570 depois (não cresceu)
--   estimados: 36 → 30 · encerrados: 43 → 43 (intocados)
--
-- ----------------------------------------------------------------------------
-- ACHADO LATERAL — o MESMO ato chega rotulado com DOIS tribunais diferentes
-- ----------------------------------------------------------------------------
-- O prazo 5713 tinha descrição "RENATO PEREZ FERNANDES · TRT-12", mas o ato é do TST.
-- Não é bug da descrição: as 4 cópias cruas do ato (publicacoes) são
--   id 303057  tribunal 'TRT-12'  tipo 'Publicação'                        354 car.
--   id 377759  tribunal 'TST'     tipo 'Lista de distribuição'             383 car.
--   id 432002  tribunal 'TST'     tipo 'DJEN/PJe'                          383 car.
--   id 432026  tribunal 'TST'     tipo 'Diário de Justiça Eletrônico Nac.' 383 car.
-- A view publicacoes_atos escolhe a cópia de texto mais longo → hoje devolve 'TST'. Quando o
-- prazo nasceu, a cópia do TST ainda não tinha chegado, e a canônica era a 'TRT-12'.
-- MEDIDO: 60 de 1.231 grupos (cnj, data) trabalhistas têm cópias com família de tribunal
-- divergente (TRT × TST).
-- CONSEQUÊNCIA: o tribunal gravado na descrição do prazo é o rótulo da cópia canônica NO
-- MOMENTO DA CRIAÇÃO, e ele muda depois. Não dá para carimbar "· ato do TST" na descrição a
-- partir desse valor — seria carimbar uma coisa que vira outra. Fica registrado; conserto de
-- verdade é normalizar `tribunal`, que continua na fila.
--
-- ----------------------------------------------------------------------------
-- CORREÇÃO DE UMA AFIRMAÇÃO MINHA
-- ----------------------------------------------------------------------------
-- Eu disse "o TST nunca gerou prazo nenhum". Estava errado: eu cruzei prazo × publicação pelo
-- `legalmail_id`, que é NULO no caminho calculado (só o caminho do Legal Mail o preenche).
-- A chave certa é `prazos.ato_chave` = cnj|data|ato_id. Cruzando certo: 3 dos 65 atos de TST
-- geraram prazo — justamente os 3 falsos de 08/09.
--
-- ----------------------------------------------------------------------------
-- O QUE FICA SEM AÇÃO (registrado de propósito)
-- ----------------------------------------------------------------------------
-- Classificação dos 65 atos de TST por natureza:
--   aviso de distribuição (não tem prazo) ... 49 atos · 17 com processo · 14/07/25–08/09/26
--   TEM ordem/prazo ......................... 11 atos ·  3 com processo · 09/07/25–25/03/26
--   pauta/ata de sessão ......................  1 ato
--   outro ....................................  4 atos
-- Os 11 com ordem são TODOS anteriores a 25/03/2026 (mais de 5 meses). NÃO backfillar: criar
-- prazo hoje para ato de março produziria 11 pendências vencidas e falsas — exatamente o
-- defeito que esta migration conserta.
--
-- 125 das 188 linhas de TST não têm processo vinculado. Prazo desses nasce como
-- "(processo a vincular)": sem cliente e sem responsável, só aparece na fila de conferência.
--
-- Volume do TST: 2 a 6 atos/mês, com pico de 25 em junho/2026. JULHO/2026 TEVE ZERO, com a
-- coleta geral do mês normal (525 atos, 110 do TRT). Cabe no ruído de um fluxo de 2–6/mês,
-- mas NÃO é prova de que a coleta não falhou naquele mês. Incerteza, não conclusão.

-- ============================================================================
-- 11/09/2026 — RECURSO TRABALHISTA (2º grau) É 8 DIAS ÚTEIS, NÃO 5 (migration trt_recurso_8_dias)
-- ============================================================================
-- Origem: ela mandou 4 PDFs "Meus Expedientes" reais do PJe (TRT-12 e TRT-15, 1º e 2º grau) e
-- pediu para conferir os prazos e ver como calcular. Extraí as 18 linhas (Data de Ciência ->
-- Prazo Final) e contei dias úteis, excluindo sáb/dom e o feriado de 07/09 (Independência).
--
-- RESULTADO, 11/09/2026:
--   Ação Trabalhista (ATOrd/ATSum) e Cumprimento de Sentença, 1º grau ... 5 dias úteis, 7 de 7
--   Recurso Ordinário / RORSum, 2º grau ...................................... 8 dias úteis, 5 de 5
--   resto (9, 10, 15, 16 dias) ........................ 6 casos, SEM explicação sem o teor do ato
--
-- 8 dias úteis é o prazo recursal correto na Justiça do Trabalho (CLT) — diferente dos 15 dias
-- úteis do CPC cível, que é o que a função implicitamente assumia ao usar N=5 sempre (o 5 vinha
-- do gabarito de 1º grau, nunca tinha sido testado contra recurso de 2º grau).
--
-- A CLASSE JÁ ESTAVA NO BANCO, só não estava sendo lida: `publicacoes_atos.classe` (medido em
-- 11/09: 448 de 1.204 atos trabalhistas preenchidos, 37% de cobertura; 48 desses já classificam
-- como recurso). Valores reais vistos: "Recurso Ordinário Trabalhista", "Recurso Ordinário -
-- Rito Sumaríssimo", "Agravo de Petição", "Agravo de Instrumento em Recurso de Revista",
-- "Recurso de Revista", "Recurso de Revista com Agravo".
--
-- A CORREÇÃO: `n_base := case when a.classe ~* 'Recurso|Agravo' then 8 else 5 end`, e o `N`
-- final continua sendo `least(n_base, n_dirigido)` — o texto dirigido, quando existe, continua
-- podendo encurtar, nunca alongar (mesma regra de sempre: erra para o lado seguro).
--
-- SEM `classe` (63% dos casos hoje), continua caindo em 5 — MESMO comportamento de antes desta
-- migration, mesmo lado seguro. Ninguém regride.
--
-- CONFERIDO após aplicar: dry-run 2025-07-01 a 2026-09-11 dá 31 atos com classe de recurso,
-- todos com N=8; os outros 880 continuam em N<=5. Nenhum prazo já gravado (`fonte=
-- 'DJEN/calculado'`) foi tocado — a função só afeta atos futuros, sem `on conflict` disparando
-- update em linha existente.
--
-- OS 4 CASOS FORA DO PADRÃO (9, 10, 15, 16 dias úteis no gabarito de 18) FICAM SEM CORREÇÃO.
-- Não dá para adivinhar sem o teor do ato — não inventar regra em cima de 1-2 amostras (regra 14
-- do LICOES.md: afirmação em documentação exige medição e data, e aqui a amostra é pequena
-- demais para virar regra).

-- ============================================================================
-- 11/09/2026 — TST: mais evidência de 15 dias úteis, mas NÃO subo o N (motivo: direção do erro)
-- ============================================================================
-- Ela mandou mais um PDF "Meus Expedientes", desta vez do TST (3ª/5ª/6ª Turmas). 3 linhas:
--   RRAg 0010055-09.2023.5.15.0051 (5ª Turma): ciência 04/09 -> prazo final 28/09 = 15 dias úteis
--   AIRR 0000824-45.2022.5.12.0028 (3ª Turma): ciência 25/08 -> prazo final 16/09 = 15 dias úteis
--   AIRR 0010691-47.2023.5.15.0027 (6ª Turma): ciência 18/08 -> prazo final 16/09 = 20 dias úteis (fora do padrão)
--
-- 2 de 3 batem em exatos 15 dias úteis — reforça os 2 outliers já vistos no gabarito de ontem
-- (CumPrSe 0010138-11 e ATOrd 0001933-49, ambos TRT 1º grau), agora com 4 casos no total.
--
-- MESMO ASSIM, NÃO estendo a régua para N=15 em nada agora. O motivo é a DIREÇÃO do erro, não a
-- falta de evidência:
--   - `N = least(n_base, n_dirigido)` sempre pega o MENOR. Se o n_base for 15 e o prazo real de
--     um caso específico for 8 (RRAg/AIRR também aparecem na classificação "Recurso|Agravo" que
--     hoje já vira N=8), o prazo calculado ficaria D14/D15 — DEPOIS do vencimento real. É
--     exatamente o erro perigoso: o time confiaria numa data que já passou.
--   - N=8 (o que já está em produção) é MENOR que 15. Se a régua certa para TST for realmente
--     15, o sistema antecipa a data — erra para o lado seguro, o mesmo raciocínio de sempre.
--   - Confundir dois fenômenos diferentes: os 2 outliers de TRT 1º grau (CumPrSe/ATOrd) e os 2
--     casos novos de TST (RRAg/AIRR) batem no MESMO número por coincidência, não necessariamente
--     pela MESMA regra jurídica — um pode ser impugnação ao cumprimento de sentença (CPC art.
--     525, 15 dias úteis, aplicado subsidiariamente) e o outro uma regra própria do TST. Sem o
--     teor do ato, tratar os 4 como uma coisa só seria inventar regra maior que a evidência.
--
-- Fica REGISTRADO para o dia em que alguém tiver o teor desses atos (RRAg/AIRR do TST
-- especificamente) e puder confirmar se 15 dias úteis é mesmo a régua do TST em recurso de
-- revista — aí sim vale considerar `tribunal ~* '^TST'` como um terceiro caso na função, com o
-- cuidado de nunca deixar o N subir sem prova poder empurrar prazo pra depois do real.

-- =====================================================================================
-- 11/09/2026 — os prazos dos PDFs "Meus Expedientes" saem da fila "a conferir"
-- =====================================================================================
-- Ela pediu: os prazos que ela mesma mandou (PDFs do próprio tribunal, "Meus Expedientes")
-- não precisam mais ficar como ESTIMADO/"a conferir" — o Prazo Final já é o dado oficial do
-- tribunal, não uma estimativa nossa. Cruzados os 27 pares (processo, Data de Ciência, Prazo
-- Final) dos 6 PDFs contra `prazos` (cumprido=false, status='estimado'):
--
--   12 prazos abertos casaram com processo cadastrado:
--     8 já tinham a data calculada IGUAL ao Prazo Final do tribunal — só confirmados
--       (ids 5714, 5726, 5736, 5797, 5740, 5770, 5773, 5774): status='confirmado'.
--     4 tinham a data calculada DIFERENTE do Prazo Final real — corrigidos para o valor do
--       tribunal e confirmados (nunca "confirma" um valor que já se sabe errado):
--         5733 (0001024-22.2025.5.12.0004): 11/09 → 16/09
--         5802 (0001806-14.2026.5.12.0030): 18/09 → 23/09
--         5775 (0010055-09.2023.5.15.0051, TST RRAg): 14/09 → 28/09 — mais uma evidência de
--           que o TST usa régua diferente do TRT (ver seção "TST" acima); aqui não é palpite,
--           é o Prazo Final oficial do próprio tribunal.
--         5800 (0011066-58.2022.5.15.0132, RORSum 2º grau): 17/09 → 22/09 — prazo calculado
--           ANTES da correção N=8 (migration trt_recurso_8_dias) entrar no ar; confirma que a
--           correção estava certa, mas o registro antigo só é corrigido agora, com prova.
--
-- ACHADO LATERAL — dois prazos fechados "em bloco sem conferência" (ver seção acima) estavam
-- com data calculada errada, e um deles vence HOJE (11/09/2026). NÃO foram alterados por esta
-- rodada — avisados diretamente para ela decidir/confirmar manualmente, porque envolve saber
-- se a peça já foi protocolada, não só corrigir uma data:
--   prazo 5732 (processo 6298, 0000998-80.2025.5.12.0050): calculado 04/09, real 11/09 (HOJE).
--   prazo 5729 (processo 6085, 0000824-45.2022.5.12.0028, TST AIRR): calculado 01/09, real 16/09.
--
-- ACHADO LATERAL 2 — processos dos PDFs sem NENHUM prazo no sistema (nem estimado, nem
-- encerrado): não é isto que ela pediu para resolver agora, mas fica registrado porque tem
-- prazo real batendo:
--   processo 6233 (0001899-87.2024.5.12.0016, ROT 2º grau): ciência 14/09, final 24/09.
--   processo 6741 (0001742-10.2026.5.12.0028): ciência 14/09, final 21/09.
--   processo 6720 (0001794-06.2026.5.12.0028): ciência ~20/08, final 14/09 (em 3 dias).
-- E 6 números de processo dos PDFs nem estão cadastrados no sistema (checar se são clientes
-- novos ou erro de transcrição do número): 0001732-38.2026.5.12.0004, 0001513-25.2026.5.12.0004,
-- 0010138-11.2026.5.15.0151, 0010691-47.2023.5.15.0027, 0011196-71.2026.5.15.0079,
-- 0011220-44.2025.5.15.0044.

-- =====================================================================================
-- 11/09/2026 — "Recurso de Revista" (TST) passa a usar 15 dias úteis, não 8 — migration
-- trt_recurso_revista_15_dias
-- =====================================================================================
-- Ela pediu para usar os PDFs que mandou para refinar o parâmetro de cálculo e parar de
-- errar. Ao cruzar os 27 pares (processo/ciência/Prazo Final) dos PDFs contra os prazos
-- abertos (ver seção "os prazos... saem da fila 'a conferir'" acima), sobrou um padrão
-- claro nos casos de TST que a correção de 8 dias (recurso trabalhista) ainda calculava
-- errado:
--
--   classe "Recurso de Revista com Agravo" (RRAg) — 1 caso — 15 dias úteis exatos
--   classe "Agravo de Instrumento em Recurso de Revista" (AIRR) — 1 caso — 15 exatos
--   classe "Agravo de Instrumento em Recurso de Revista" (AIRR, outro processo) — 20 dias
--     úteis (outlier, mais alto que 15 — não contradiz o piso de 15, só não o explica)
--
-- Nenhum caso de "Recurso de Revista" (em qualquer variação) bateu em 8 dias ou menos.
-- `processos.tribunal` NÃO serve para distinguir TST de TRT aqui — o campo carrega o
-- tribunal de ORIGEM do processo (ex.: "TRT12"), não o órgão que praticou o ato (mesmo
-- problema já documentado para o aviso de distribuição do TST). A classe do ATO em si já
-- resolve: qualquer classe contendo "Recurso de Revista" — sozinho, com Agravo, ou como
-- Agravo de Instrumento — é o recurso de competência do TST, com prazo diferente do
-- Recurso Ordinário (TRT, 8 dias, CLT art. 895 expresso). A hipótese jurídica mais provável
-- é a aplicação subsidiária do CPC (art. 1.003 §5º, 15 dias úteis) para o instrumento que a
-- CLT não define em 8 dias — mas isso é hipótese, não prova; o que está provado é o número.
--
-- "Agravo" isolado (Agravo de Petição, agravo genérico sem "de Revista") CONTINUA em 8 —
-- sem nenhuma evidência de que seja diferente, e 8 é o lado seguro quando não se sabe.
--
-- Medido (dry-run 2025-07-01 a 2026-09-11, antes/depois):
--   17 atos têm classe com "Recurso de Revista" (13 AIRR + 3 RRAg + 1 "com Agravo");
--   3 já tinham prazo gravado (não tocados); 14 ainda não — esses passam de N=8 para N=15.
--   Todos os outros 894 candidatos do dry-run permanecem exatamente iguais (871 em N=5,
--   18 em N=8 — os "Recurso Ordinário"/RORSum/Agravo de Petição continuam intocados).
--   Nenhum prazo já gravado é alterado por esta migration — só atos futuros/não gravados.
--
-- ============================================================================
-- 14) Conferência contra 3 prints "Meus Expedientes" (TRT-12 Joinville + TRT-15) — 14/09/2026
-- ============================================================================
-- Ela mandou 3 prints sem texto (mesmo padrão de sempre). 13 CNJs transcritos e cruzados.
--
-- BATEU (2): 0001742-10.2026.5.12.0028 (21/09) e 0011066-58.2022.5.15.0132 (22/09) — o
-- primeiro só precisava passar de status='estimado' para 'confirmado' (feito).
--
-- 3 dias-a-menos que o print (0001337-59, 0001359-63, 0002658-17): refiz a conta
-- (`becker_dias_uteis` aninhado, mesmos parâmetros) e ela bate EXATO com o valor gravado —
-- ou seja, a fórmula está correta para a disponibilização que o sistema capturou; se há erro,
-- é na captura da data (DJEN pode estar 1 dia adiantado do que a tela do tribunal mostra) ou
-- na minha transcrição do print. Testei via Legal Mail `lawsuit/case-files` (grátis) se a
-- movimentação interna confirma outra data — não dá pra confirmar por esse caminho: o campo
-- "data_movimentacao" do case-files é a data do ATO PRATICADO, não da disponibilização no
-- DJEN (que é o marco que conta prazo), então divergem por natureza, não por erro. Fica em
-- aberto — pedido a ela pra reconferir os 3 prints antes de mexer em qualquer coisa.
--
-- ACHADO REAL (0001806-14.2026.5.12.0030, prazo id 5802): gravado 23/09 e já 'confirmado',
-- mas a fórmula padrão (N=5) dá 18/09 pros mesmos parâmetros que a própria descrição do
-- prazo declara. Motivo encontrado: o ato de 10/09 é ciência de SENTENÇA (confirmado via
-- case-files: há "Sentença" datada 09/09 nos autos), que pede prazo de Recurso Ordinário
-- (8 dias úteis, CLT art. 895) — e 23/09 bate exatamente com N=8 pros mesmos parâmetros.
-- Ou seja, o valor gravado parece ter sido corrigido à mão por alguém em algum momento
-- (reconhecendo que era recurso, não despacho comum) mas a `descricao` ficou desatualizada
-- (ainda diz "+1+5"). Isso é sintoma de uma lacuna real da função: `trt_gera_prazos` só
-- decide N=8 pela CLASSE do ato (Recurso|Agravo), nunca pelo CONTEÚDO ("ciência da
-- Sentença") — uma sentença de 1º grau intimada com classe "Ação Trabalhista" (não
-- "Recurso") cai em N=5 por padrão, do lado perigoso (antecipa, mas o texto já avisa "cita
-- N dias" quando aplicável). Não mexida ainda — o print mostra 24/09, 1 dia além até do
-- valor corrigido a mão (23/09); perguntado a ela se lembra de ter corrigido este prazo.
--
-- 0001794-06.2026.5.12.0028 (sem prazo nenhum, sem cliente): achado o ato de 19/08 ("emende
-- a petição inicial... quinze dias", RECLAMANTE Beatriz Luiz da Silva x RECLAMADO Unicostura
-- Ltda) que nunca virou prazo. Causa: o cron `trt_prazos_diario` roda com janela
-- `current_date-15..current_date` (15 dias corridos) — o ato saiu da janela ~03/09 e nunca
-- mais foi reprocessado. Verbo "emende" também não está na lista reconhecida pelo regex de
-- N-dirigido (só encurtaria, nunca alongaria, mas mesmo dentro da janela teria gerado N=5 em
-- vez de 15). Não criado ainda — falta saber de quem é o processo (autora ou ré) pra saber
-- se o prazo é nosso.
--
-- 6 CNJs sem `processos` cadastrado, com histórico real de intimação (desde 09/2025 em um
-- caso): 0001933-49, 0001732-38, 0011196-71, 0010138-11, 0011176-49, 0011220-44. Criados
-- agora como processos "bare" (sem cliente, `observacoes` registrando a origem) — o trigger
-- `trg_processos_relinca_orfaos` religou automaticamente as `publicacoes` E os `prazos`
-- órfãos que o cron `trt_prazos_diario` já tinha gerado silenciosamente pra eles nos últimos
-- dias (existiam como "(processo a vincular)", invisíveis em qualquer tela porque não tinham
-- processo nem cliente). Rodado também `legalmail-autos` action=sync_ids (grátis, `lawsuit/all`)
-- pra popular `lm_idprocessos` — 143 processos atualizados no total (efeito colateral bom,
-- não só os 6). ACHADO MAIS SÉRIO DESTE GRUPO: prazo id 5777 (0011176-49.2023.5.15.0091,
-- Recurso Ordinário em Órgão Especial) tinha data calculada 10/09/2026 — JÁ VENCIDO (hoje é
-- 14/09) — e ficou 100% invisível até agora porque o processo nunca existiu no sistema. Não
-- fechado nem tocado: falta entender se já foi respondido (há uma "Decisão" de 11/09 nos
-- autos via Legal Mail, que pode já ser a resposta do tribunal a isso) antes de qualquer ação.
-- Reportado a ela para triagem imediata.
--
-- Sondagem usada (`legalmail-varredura-probe`, case-files + lawsuit/all, tudo grátis) já
-- neutralizada.
--   Nenhum prazo já gravado é alterado por esta migration — só atos futuros/não gravados.
--
-- ============================================================================
-- 15) CORRIGIDO: ciência leva DOIS dias úteis após a disponibilização, não um — 14/09/2026
-- ============================================================================
-- Ela mandou um caso novo com as datas oficiais escritas por ela (não estimadas):
-- `0001706-96.2026.5.12.0050` (VALDINEIA FONSECA DE SOUZA x JAH AÇAI JOINVILLE LTDA, nosso
-- cliente): Disponibilização 03/09 (qui), Publicação 04/09 (sex), início da contagem 07/09
-- (seg), 8 dias úteis, termina 17/09. E confirmou por escrito a regra: "disponibilização, o
-- dia da publicação (que é o primeiro dia útil seguinte ao da disponibilização) e o início
-- efetivo do prazo, que ocorre no primeiro dia útil seguinte ao da publicação."
--
-- Base legal: Lei 11.419/2006 art. 4º §3º (publicação = 1º dia útil seguinte à
-- disponibilização) + CPC art. 224 c/c 231, II (a contagem do prazo começa no 1º dia útil
-- seguinte à PUBLICAÇÃO, não à disponibilização). Ou seja, são DOIS saltos de dia útil, não
-- um só. A função sempre usou só um
-- (`becker_dias_uteis(becker_dias_uteis(disp,1,abr),n,abr)`), fórmula "validada 6/6 contra o
-- PJe" em 09/09 (seção 1) — o gabarito de 6 nunca cruzou uma disponibilização numa
-- sexta-feira nem foi conferido contra a "Data de Publicação" separada, só contra o "Prazo
-- Final" mostrado na tela, então o erro de 1 dia útil passou despercebido até agora.
--
-- CONFERIDO com dados reais antes de mexer (nunca só no exemplo dela):
--   `0001337-59` (disp 09/09 qua): +2 → 11/09; +5 → 18/09. Print do tribunal: 18/09. BATEU.
--   `0001359-63` (disp 08/09 ter): +2 → 10/09; +5 → 17/09. Print: 17/09. BATEU.
--   `0001806-14` (disp 10/09 qui, é Sentença → Recurso Ordinário, N=8): +2 → 14/09; +8 →
--     24/09. Print: 24/09. BATEU EXATO — resolve também o mistério do prazo 5802 (seção 14,
--     grupo C): o valor gravado (23/09) provavelmente foi corrigido à mão por alguém usando
--     N=8 mas ainda com a ciência errada de +1; com a ciência certa (+2) E N=8, dá 24/09.
--   `0002658-17` (disp 03/09 qui): +2 → 07/09; +5 → 14/09. Print: 15/09. NÃO bateu — mas
--     esse caso já tinha aviso "texto cita 5 dias — conferir" (pode ser problema à parte, no
--     N, não na ciência). Não investigado a fundo, fica registrado.
--   `0001742-10` (disp 11/09 sex): a rodada anterior tinha esse como "bateu exato" com a
--     fórmula ANTIGA (21/09). Com +2 daria 22/09. Não dá pra reconferir o print original
--     (não guardei a imagem) — hipótese mais provável é erro de transcrição minha (21 vs 22).
--     Fica pendente de reconferência manual, não impediu a correção da regra geral.
--
-- BOA NOTÍCIA: o erro (usar +1) sempre calculava uma data 1 dia útil MAIS CEDO que a real —
-- nunca fez perder prazo (o erro sempre foi pro lado seguro, "sobra tempo"), só gerava alarme
-- de urgência falso e podia levar a confirmar/protocolar antes da hora achando que o prazo
-- era mais curto do que é.
--
-- FEITO: `becker_dias_uteis(disp,1,abr)` → `becker_dias_uteis(disp,2,abr)` em
-- `trt_gera_prazos` (CREATE OR REPLACE, mesma função, só essa linha + a descrição gerada
-- passa a dizer "+2+N" em vez de "+1+N"). Reprocessados os 21 prazos que ainda estavam
-- `status='estimado'` (nunca toquei `confirmado`/`cumprido` — mesma disciplina de sempre):
-- deletados pelo id exato e regerados via `trt_gera_prazos('2026-08-25','2026-09-14',true)`,
-- que também pegou 6 atos novos que a janela mais larga alcançou (27 gravados no total).
-- Conferido: nenhuma duplicata de mesmo evento (processos com mais de um prazo aberto agora
-- são sempre atos DIFERENTES, ato_chave com data/id distintos — checado um a um nos casos
-- com 2+ prazos DJEN/calculado).
--
-- NÃO MEXIDO (de propósito): os prazos já `confirmado`/`cumprido` anteriores a hoje. A
-- conferência mostrou que boa parte dos `confirmado` bate com a fórmula ANTIGA (+1) — o que
-- é esperado, já que foi o valor que o sistema sugeriu e alguém clicou "Data confere" em
-- cima dele; não é prova de que a data real do tribunal é essa, só que ninguém a contestou.
-- Ou seja, é bem possível que existam prazos `confirmado` no passado que também estejam 1
-- dia útil adiantados — mas corrigir isso é uma decisão à parte (reabrir prazo confirmado
-- exige a mesma prova que fechar um, pela regra de `prazo_nao_fecha_por_data`), não entra
-- nesta migration.
--
-- UI (`site/index.html`, `verPrazo`): a linha "Conta:" e o tooltip do selo "⚠ ESTIMADO"
-- atualizados pra dizer "+2 dias úteis (publicação + ciência)" em vez de "+1 dia útil
-- (ciência)". Também aproveitado o mesmo commit para reformatar a caixa cinza do texto da
-- intimação (pedido dela, print à parte): nova `_corpoIntimacao(txt)` remove o cabeçalho de
-- metadados repetido (Fonte/Disponibilização/Status do prazo/Destinatário/ID do evento — já
-- aparecem na caixa "PRAZO E CONTA" acima) antes de exibir, só isso, não mexe no dado gravado.
--
-- ============================================================================
-- 16) CORRIGIDO: "ciência da Sentença" é N=8 (Recurso Ordinário), mesmo sem classe "Recurso"
-- ============================================================================
-- Ela perguntou: "quantos dias não tem na intimação/despacho? mesmo sem data final não fala
-- quantos dias são?" Medido no universo real que `trt_gera_prazos` processa (TRT/TST, sem
-- "data final", sem pauta/ata — 1.014 atos em 14/09/2026):
--   654 de 1.014 (65%) não citam NENHUM número de dias/horas no texto — confirma a intuição
--   dela, a maioria dos despachos do TRT simplesmente não fala quantos dias são.
--   338 (33%) citam algum número perto de "dias", mas quase sempre é norma citada (ex. art.
--   895 CLT) ou prazo de outra parte — só 19 de 1.014 (1,9%) têm ORDEM DIRIGIDA de verdade.
-- Por isso a função depende do `n_base` por classe, não tem como confiar em achar o número no
-- texto na maioria dos casos.
--
-- Nessa mesma investigação achei um bug sistemático: 75 atos têm texto "ciência da Sentença"
-- (que abre prazo de Recurso Ordinário, 8 dias úteis pela CLT) mas a `classe` do ato ainda é
-- a da ação original de 1º grau ("Ação Trabalhista", ou sem classe) — não "Recurso" — então
-- caíam em N=5 por engano. Mesmo problema, maior escala, do que resolveu o mistério do prazo
-- 5802 em 0001806-14 (seção 14/15) — lá era 1 caso, aqui são pelo menos 75.
--
-- Ela confirmou com uma tabela de referência de prazos por tipo de manifestação trabalhista:
-- Recurso Ordinário, Contrarrazões, Agravo de Instrumento, Agravo de Petição e Recurso de
-- Revista são todos 8 dias; só Embargos de Declaração é 5 (tipo diferente de manifestação,
-- não conflita com esta regra — se o texto também mencionar embargos com prazo dirigido, o
-- `n_dirigido`/`dias_citados` já existente encurta sozinho, sem caso especial).
--
-- FEITO: `n_base` em `trt_gera_prazos` agora usa N=8 quando o texto casa
-- `ci[êe]ncia d[ae] Senten[çc]a` E a classe NÃO é já Recurso/Agravo/Revista. Deixados de fora
-- (mantém N=5, sem generalizar sem olhar) os 3 casos "Homologação de Transação Extrajudicial"
-- (sentença homologatória, normalmente sem recurso cabível) e os 2 "Cumprimento Provisório de
-- Sentença" (execução — agravo de petição também é 8 dias, mas contexto diferente).
--
-- IMPACTO IMEDIATO: zero — nenhum dos 27 prazos `status='estimado'` reprocessados na seção 15
-- casa com "ciência da Sentença" (conferido). A correção vale só pra atos futuros a partir de
-- agora (próxima rodada do cron `trt_prazos_diario`, ou qualquer novo ato do dia a dia). Os
-- 75 atos históricos já identificados não foram tocados — a maioria já tem prazo gravado com
-- algum status (confirmado/cumprido/vencido antigo), e a mesma disciplina de sempre (nunca
-- reabrir prazo fechado sem prova) se aplica.
--
-- ============================================================================
-- 17) BACKFILL retroativo: janela larga (desde 2023) pra pegar o que nunca foi processado
-- ============================================================================
-- Ela pediu direto: "arrumou no sistema já? todos que estão lá e são TRABALHISTA?" — depois
-- de saber que 67 dos 75 atos de "ciência de Sentença" nunca tiveram prazo nenhum gerado
-- (fora da janela de 15 dias do cron `trt_prazos_diario`), pediu pra rodar numa janela larga
-- mesmo sabendo que ia trazer muita coisa histórica.
--
-- Rodado `trt_gera_prazos('2023-10-30','2026-09-14', false)` (dry-run primeiro): 936
-- candidatos, TODOS já com `prazo_calculado` no passado (disponibilização entre jul/2025 e
-- ago/2026) — não é só os 67 de Sentença, é qualquer ato TRT/TST de qualquer tipo que nunca
-- caiu numa janela de 15 dias.
--
-- Antes de gravar, mostrei o número real (936, não os 67 que motivaram a pergunta) e perguntei
-- de novo — ela respondeu "faz os em aberto ainda melhor só", ou seja: só os que ainda
-- parecem realmente pendentes, não gravar tudo às cegas.
--
-- FEITO (commit + filtro na sequência, mesma transação de raciocínio):
--   1. Rodado `trt_gera_prazos(..., true)` — gravou os 936 (ids 5879-6814).
--   2. Deletados os que NÃO parecem mais "em aberto de verdade", usando só sinais que já
--      temos no próprio banco (sem custo, sem chamada de API):
--        - processo sem `cliente_id`... não, sem `processo_id` vinculado (167) — não dá pra
--          julgar "ainda aberto" sem processo cadastrado, mesma disciplina dos 6 CNJs órfãos
--          da seção 14 (cadastrar processo é decisão à parte, não bloqueia aqui).
--        - processo com `situacao` diferente de "Ativo" (marcado arquivado/encerrado).
--        - processo que já tem outro prazo MAIS NOVO gravado antes desta operação (o caso
--          se moveu — o prazo antigo virou moot).
--   Restaram **316 prazos** (de 936) — todos `status='estimado'`, `cumprido=false`,
--   disponibilização entre 16/07/2025 e 02/09/2026. 23 deles já usam a regra nova N=8 (seção
--   16, "ciência de Sentença"). 7 ainda sem cliente vinculado (processo existe, cliente não).
--
-- NÃO é garantia de 100% "ainda aberto" — é o melhor filtro dá pra fazer só com os dados que
-- já temos, sem gastar em API por 936 consultas. Pode sobrar prazo falso-positivo (caso
-- resolvido fora do sistema, sem deixar rastro de prazo mais novo aqui) — ela sabia disso e
-- decidiu mesmo assim. Nenhum prazo pré-existente (`id<=5878`, qualquer status) foi tocado.
--
-- REVERTIDO na sequência (mesma conversa): ela viu que os 316 mantidos eram TODOS vencidos
-- (nenhum de hoje pra frente — óbvio em retrospecto, já que a fonte é histórica) e pediu
-- "deixa só os de hoje pra frente, os vencidos pode excluir". Como literalmente 0 dos 316
-- tinham `data >= current_date`, isso equivale a desfazer o backfill inteiro — deletados os
-- 316 (ids 5879-6814, conferido antes de apagar que TODOS tinham `data < current_date`).
-- Banco voltou ao estado de antes da seção 17. A correção da fórmula (seções 15 e 16)
-- continua valendo só pra atos futuros/dentro da janela normal do cron — não geramos mais
-- retroativo de prazo já vencido.
--
-- ============================================================================
-- 18) CORRIGIDO: Recurso de Revista é N=8, não N=15 — achado que veio de um caso real grave
-- ============================================================================
-- A regra de N=15 pra "Recurso de Revista" (migration trt_recurso_revista_15_dias, seção 13)
-- tinha sido validada contra a tela "Meus Expedientes" do próprio tribunal — PDFs reais que
-- ela mandou, nenhum caso batendo em 8 dias, todos em 15+. Pareceu prova sólida na hora.
--
-- Ela então lembrou de um caso real: um prazo que o TRIBUNAL mostrava como 14 dias pra
-- fechar, mas o certo era 8 — o escritório confiou no número maior, protocolou dentro do
-- prazo que o tribunal indicava, e o próprio tribunal considerou INTEMPESTIVO (fora do prazo
-- real). Ou seja: a tela do tribunal pode mostrar prazo ERRADO — maior que o legal — e foi
-- exatamente esse tipo de erro que gerou dano real antes. A "validação contra Meus
-- Expedientes" da seção 13 pode ter só copiado esse mesmo erro de exibição do tribunal, não
-- confirmado a lei.
--
-- Ela então mandou a fonte oficial (não mais tela de tribunal, texto de lei): CLT art. 896 c/c
-- 900 — Recurso de Revista é 8 dias úteis, igual Recurso Ordinário, Agravo de Instrumento,
-- Agravo de Petição e Contrarrazões/Contraminuta. Confirmado, e é consistente com a "Regra
-- de Ouro dos 8 dias" da Justiça do Trabalho — o outlier era o N=15, não o contrário.
--
-- FEITO: removida a classe especial "Recurso de Revista" → 15; agora cai no mesmo bucket de
-- "Recurso|Agravo" → 8, junto com RO/AI/AP. `becker_dias_uteis` e a regra de +2 dias úteis de
-- ciência (seção 15) continuam iguais — só o N mudou.
--
-- IMPACTO NOS PRAZOS JÁ GRAVADOS: ZERO precisou mudar — conferido, não existe HOJE nenhum
-- prazo com N=15 em `status` nenhum (nem estimado, nem confirmado). Os 17 atos históricos de
-- Recurso de Revista identificados (seção 14) ficaram assim: 3 já tinham prazo próprio com
-- N=5 (de antes da regra de 15 sequer existir — mais curto que os 8 corretos, lado seguro,
-- não mexidos, 2 já `encerrado` e 1 `confirmado`) e os outros 14 NUNCA geraram prazo nenhum
-- (fora da janela de 15 dias do cron, mesmo buraco da seção 17). Rodado dry-run com N=8 pra
-- ver quais desses 14 ainda estão em aberto: TODOS os 13 candidatos simulados (um dos 14 caiu
-- fora por já ter prazo) têm `prazo_calculado` entre abr/2026 e 31/08/2026 — ou seja, TODOS
-- já vencidos também, igual o backfill da seção 17. Por instrução dela ("os que já foram só
-- ignorar"), não gerados — mesma decisão de ontem, mesmo motivo.
--
-- Outros pontos da fonte oficial que ela mandou, já batendo com o que o sistema faz:
--   Embargos de Declaração = 5 dias (art. 897-A) — cai no "else 5" default, sem precisar de
--     caso especial.
--   Embargos à Execução / Impugnação à Sentença de Liquidação = 5 dias (art. 884) — confirma
--     que excluir "Cumprimento Provisório de Sentença" da regra de Sentença→8 (seção 16) foi
--     a decisão certa; esse é um contexto de execução com prazo de 5, não de recurso com 8.
--   Prazo em dobro pra Fazenda Pública/MPT (Decreto-Lei 779/69) — NÃO implementado, sinalizado
--     a ela como lacuna conhecida, pendente de saber se o escritório tem esse tipo de caso.
--
-- ============================================================================
-- 19) SOBRESCRITOS prazos trabalhistas já confirmado/cumprido — decisão explícita dela
-- ============================================================================
-- Depois da correção da seção 18, ela pediu direto: "muda os prazos ja gravados d
-- etrabalhista". Perguntado se isso incluía `confirmado`/`cumprido` (não só `estimado`, que
-- já estava certo) — ela confirmou que sim, mesmo sabendo que quebra a disciplina de nunca
-- reabrir prazo fechado sem prova. Decisão dela, registrada.
--
-- Recalculados TODOS os prazos `fonte='DJEN/calculado'` com `status='confirmado'` OU
-- `cumprido=true` (isso inclui `confirmado`, `cumprido`, `encerrado` e `descartado` — todo
-- prazo trabalhista já gravado, não só os em aberto), usando a fórmula atual completa: +2
-- dias úteis de ciência (seção 15) + N correto por classe/texto, incluindo Sentença→8 (seção
-- 16) e Recurso de Revista→8 (seção 18). Só os campos `data`/`data_prazo` e o trecho
-- "+N+M dias úteis" da `descricao` foram sobrescritos — `status`/`cumprido`/`cumprido_em`/
-- `cumprido_por` NÃO foram tocados, nenhum prazo fechado foi reaberto.
--
-- 64 prazos recalculados (de todos com ato_chave e status confirmado/cumprido/encerrado/
-- descartado). Achados que pedem atenção:
--
--   **3 prazos CONFIRMADO (ainda em aberto, cumprido=false) ficaram VENCIDOS depois da
--   correção** — antes pareciam confortáveis, a data real já passou:
--     id 5714 — EDILSON ANTONIO DA SILVA (proc. 0000023-84.2026.5.12.0030, TRT-12,
--       resp. Samaira) — era 16/09 (ou o que estava confirmado), agora 11/09 (3 dias vencido).
--     id 5736 — KAUE BRIGADEIRO DOS SANTOS (proc. 0001216-43.2026.5.12.0028, TRT-12,
--       resp. Samaira) — mesma disp. 01/09, mesmo N=5, agora 11/09.
--     id 5773 — JOSÉ JUAREZ DA SILVEIRA (proc. 0002620-60.2025.5.12.0030, TRT-12,
--       resp. Samaira) — mesma disp. 01/09, mesmo N=5, agora 11/09.
--   Como esses 3 continuam `cumprido=false`, e a tela já não mostra mais "Vencidos" (seção
--   17/decisão de ontem), eles vão SUMIR da lista principal de Prazos sem avisar ninguém.
--   Reportado a ela com urgência — precisam de conferência humana imediata (será que já foi
--   protocolado e só não foi marcado? é caso real perdido?), não é para ignorar.
--
--   **id 5775 — Recurso de Revista (DIEGO SALES LIMA, TRT-15) andou 10 dias pra TRÁS**:
--   estava confirmado em 28/09, virou 18/09 — efeito direto da correção N=15→8 da seção 18.
--   Ainda não vencido (18/09 é daqui a poucos dias úteis), mas a folga que alguém pensava ter
--   encolheu bastante. Também reportado com destaque.
--
--   id 5824 (0001742-10, ver seção 14 grupo B) andou de 21/09 para 22/09 — é o caso que já
--   estava pendente de reconferência manual (print antigo dizia 21/09, a fórmula nova dá
--   22/09). Continua sem resolução — ela ainda não confirmou se o print estava certo.
--
--   id 5802 (0001806-14, ver seções 14/15) andou de 23/09 para 24/09 — agora bate EXATO com
--   o print do tribunal (24/09) que já tínhamos registrado como não resolvido. Resolvido.
--
-- Os outros ~58 prazos recalculados são `encerrado`/`descartado` (já fechados sem
-- conferência individual antes) ou `confirmado` com data ainda confortavelmente no futuro —
-- só correção de registro histórico, sem ação pendente.
--
-- REVISADO na sequência (mesma conversa): ela achou normal os 3 confirmado ficarem vencidos
-- ("não tem problema") e deu a regra final, igual à da seção 17: **excluir tudo que, depois
-- da correção, ficou com data < hoje — não importa se era confirmado, encerrado ou
-- descartado — e manter (pra conferência manual) só o que continua com data >= hoje.**
-- Reafirma a regra de sempre ("vencido já não faz mais nada, não tem porque mostrar") — os 3
-- confirmado-agora-vencidos entram na mesma lógica, não são exceção.
--
-- Deletados 43 dos 64 (os com `data < current_date` depois da seção 19, incluindo os 3
-- confirmado): 3 confirmado + 40 encerrado. Mantidos 19 com `data >= current_date` — todos os
-- `confirmado` que sobraram (incluindo o Recurso de Revista, id 5775, agora 18/09) e alguns
-- `encerrado`/`descartado` cuja data recalculada bateu ser hoje/futuro por coincidência.
--
-- ============================================================================
-- 21) FERIADO REAL: suspensão TRT-12 de 11/09/2026 (chuvas, Ato Seap nº 11/2026)
-- ============================================================================
-- Ela mandou um resumo de terceiro alegando essa suspensão, citando fonte de Instagram — testei
-- (WebSearch) e NÃO achei confirmação: as suspensões reais de 2026 do TRT-12 por chuva que
-- apareceram foram todas em outubro (4-6, 9-11, 16-18) e uma em 26-29/09 por instabilidade do
-- PJe, não chuva. Reportei a ela como não verificada, pedindo a fonte oficial antes de mexer.
--
-- Ela mandou o PDF da página oficial (portal.trt12.jus.br), publicada HOJE 11/09/2026 16h16:
-- "Prazos processuais de sexta-feira (11/9) são suspensos devido às fortes chuvas" — real,
-- confirma "Ato Seap nº 11/2026". O WebSearch simplesmente não tinha indexado a notícia ainda
-- (publicada horas antes da minha busca). Lição: fonte de terceiro sem link oficial verificável
-- (Instagram) foi certo desconfiar, mas a notícia em si era verdadeira — vale sempre pedir a
-- fonte primária antes de descartar OU de aceitar.
--
-- FEITO: inserido `('2026-09-11','Suspensão de prazos processuais — fortes chuvas (Ato Seap nº
-- 11/2026)','TRT12')` em `feriados`. Como `becker_dias_uteis` já lê `feriados` via EXISTS por
-- abrangência, isso corrige automaticamente qualquer cálculo futuro sem mexer em código.
--
-- Recalculados TODOS os prazos TRT-12 `fonte='DJEN/calculado'` (qualquer status, mesmo padrão
-- da seção 19) cuja janela de contagem atravessa 11/09 — 24 prazos, todos andaram exatamente
-- +1 dia útil pra FRENTE (nunca pra trás — excluir um dia útil só pode alongar, nunca
-- encurtar, então não existe risco de criar um "vencido" novo aqui; nenhuma exclusão foi
-- necessária desta vez).
--
-- ACHADO CRÍTICO: 2 prazos (ids 5863, 5866 — SEBASTIÃO MARCAL DE FREITAS e um processo a
-- vincular, mesma disp. 01/09) tinham vencimento calculado EXATAMENTE em 11/09 — o dia
-- suspenso. Antes da correção, hoje (14/09) eles já apareceriam vencidos (3 dias). Com a
-- correção, o vencimento real é HOJE (14/09) — não amanhã, não passado, hoje. É o mesmíssimo
-- card do SEBASTIÃO que ela mandou de print no começo da sessão perguntando "esse estimado é
-- como?" — o print de fato estava mostrando prazo errado, só que por causa desse feriado que
-- faltava, não só pela fórmula antiga.
--
-- PENDÊNCIA NOVA: id 5802 (0001806-14, Sentença→Recurso Ordinário, ver seções 14/15) andou de
-- 24/09 pra 25/09 com essa correção — mas o print do tribunal que ela mandou (conferido como
-- "bateu exato" na seção 15) dizia 24/09. Se aquele print já foi tirado DEPOIS do Ato Seap
-- (bem provável, já que o ato é de hoje e o print é de dias atrás — precisa checar a data do
-- print), o 24/09 do próprio tribunal pode já estar certo e a nossa conta pode estar
-- contando 11/09 como suspenso quando o tribunal, na prática, não aplicou a suspensão a esse
-- prazo específico (ela pode ter sido só de 1º grau, e esse processo já estar em 2º grau/TST
-- — não confirmado). Fica registrado como discrepância aberta, não corrigido às cegas.

-- ============================================================================================
-- 14/09/2026 — CNJ 0010138-11.2026.5.15.0151 (Tania Aparecida da Silva x Banco J. Safra) NÃO
-- é cliente da Becker Advocacia — é cliente do Dr. Umberto Becker (pai da Cibele), escritório/
-- advogado diferente. Ela confirmou explicitamente: "os que são do Umberto não são nosso".
--
-- ORIGEM: esse CNJ era 1 dos 6 "processos órfãos" cadastrados em 13/09 (seção "conferência
-- dos 3 prints... 13 CNJs") sem cliente identificável no texto — entrou com cliente_id=null e
-- advogado_responsavel='Cibele Becker' só por padrão do formulário, nunca confirmado de
-- verdade (processo id=6773).
--
-- NÃO bastava só deletar o processo: 20 publicações desde 02/02/2026 até 04/09/2026 (caso
-- ativo, recorrente) — a próxima intimação desse CNJ ia gerar um prazo novo "(processo a
-- vincular)" de novo, porque trt_gera_prazos processa qualquer ato trabalhista, sem filtrar
-- por cliente.
--
-- FEITO:
--   1. Nova tabela `processos_nao_nossos (cnj text primary key, motivo, criado_em,
--      criado_por)` — mesmo padrão de `feriados`: uma tabela pequena que a função já lê
--      sozinha, sem precisar mexer em código de novo a cada caso novo.
--   2. `trt_gera_prazos` (CTE _cand) ganhou
--      `and not exists (select 1 from processos_nao_nossos x where x.cnj = a.cnj)` no WHERE —
--      a.cnj já vem em dígitos, bate exato com o cnj do ato_chave.
--   3. INSERT em processos_nao_nossos pro CNJ 00101381120265150151.
--   4. DELETE do processo id=6773 — cascata (prazos.processo_id e movimentacoes.processo_id
--      são ON DELETE CASCADE, conferido via pg_constraint) apagou sozinha o único prazo aberto
--      (id 5852, TRT-15, venceria 16/09) e as 33 movimentações; publicacoes.processo_id é ON
--      DELETE SET NULL — as 20 publicações continuam gravadas, só voltaram a processo_id=null
--      (mesmo estado de antes do cadastro errado de 13/09). Conferido antes: nenhum dado real
--      do escritório ligado a esse processo (financeiro/documentos/atendimentos/audiências/
--      tarefas/alvarás/petições/processo_clientes — todos zero).
--
-- CONFERIDO: dry-run trt_gera_prazos(current_date-1, current_date+1, false) não traz mais
-- esse CNJ na lista de candidatos.
--
-- OS OUTROS 5 processos órfãos do mesmo lote de 13/09 (mesmo padrão: cliente_id=null,
-- advogado_responsavel='Cibele Becker' só por padrão, nunca confirmado) foram listados pra ela
-- com as partes de cada um, mas NENHUM foi tocado nesta rodada — só a Tania, que foi
-- confirmada:
--   0001933-49.2026.5.12.0030 (TRT-12) — GLAUCIA DOS SANTOS x CRISTIANE RAMOS
--   0001732-38.2026.5.12.0004 (TRT-12) — JOSEFA ALINE BARBOZA x FERREIRA MÃO DE OBRA LTDA
--   0011196-71.2026.5.15.0079 (TRT-15) — SILVIA BORGES DOS SANTOS x SAFRA CRÉDITO, FINANC. E
--     INVESTIMENTO S.A. — mesmo padrão do caso da Tania (banco Safra como réu), vale conferir
--   0011176-49.2023.5.15.0091 (TRT-15) — PAULO SERGIO ZAMPIERI E OUTROS (texto não deixa claro
--     quem é recorrente/recorrido)
--   0011220-44.2025.5.15.0044 (TRT-15) — EMERSON BONFIM FRANCISCO E OUTROS (3)

-- ============================================================================================
-- 14/09/2026 — mais 21 CNJs excluídos: "Umberto Carlos Becker" (OAB/PR 15743) como advogado
-- não é nosso, mesmo quando Cibele Becker Friedrichsen também aparece listada no mesmo ato
--
-- Depois da exclusão do CNJ da Tania (seção anterior), ela confirmou a regra de forma mais
-- ampla: "isso os que tem umberto nao é nosso" — qualquer processo onde Umberto Carlos Becker
-- aparece como advogado não é da Becker Advocacia, mesmo nos casos em que ele aparece JUNTO
-- com Cibele Becker Friedrichsen (e frequentemente também Fernanda Golinelli Gongora e
-- Vanderlei Iori) — não é um sinal de que o caso é nosso, é o time do escritório do Umberto.
--
-- Busca em `publicacoes.texto` por "umberto" (excluindo falso positivo "Humberto Theodoro
-- Júnior", jurista citado em petições) achou 22 CNJs distintos. Maioria são ações contra
-- bancos (CEF, Banco J. Safra, Bradesco Financiamentos, BMG, Votorantim, Itaú) — sugere um
-- time de advogados que atua em causas bancárias, registrado com Cibele em conjunto.
--
-- 3 desses 22 já tinham processo cadastrado:
--   - id 6732 (0002335-53.2021.4.03.6202, TRF3) — sem cliente, 0 prazos/financeiro/documentos,
--     18 movimentações — deletado (cascata limpou as movimentações; publicações desvinculadas).
--   - id 6745 (0001408-71.2026.5.09.0670, TJSC) — sem cliente, 1 audiência auto-extraída do
--     Legal Mail (id 129, sem confirmação humana) — audiência deletada primeiro (FK não é
--     cascade), processo deletado depois; publicações desvinculadas.
--   - id 6101 (0010055-09.2023.5.15.0051, TRT-15) — **NÃO EXCLUÍDO**: diferente dos outros,
--     tem cliente real vinculado (DIEGO SALES LIMA, id 1323, cadastrado em 08/06/2026 — 3
--     meses antes desta sessão, não foi um cadastro apressado desta sessão) e 1 prazo em
--     aberto rastreado. Fica de fora da exclusão até ela confirmar especificamente este caso
--     — é diferente o suficiente do padrão (processo órfão recém-cadastrado sem cliente) pra
--     merecer confirmação à parte antes de mexer num cliente real já em acompanhamento.
--
-- FEITO: INSERT dos 21 CNJs restantes em `processos_nao_nossos` (mesma tabela da seção
-- anterior). Nenhum prazo já gravado (`prazos.ato_chave`) referenciava esses CNJs — nada foi
-- tocado além do cadastro dos 2 processos órfãos acima.
--
-- CONFERIDO: dry-run trt_gera_prazos('2020-01-01', current_date+1, false) não traz mais
-- nenhum desses 21 CNJs, em nenhuma janela.

-- ============================================================================================
-- 22) REVERTIDA a seção 15 — "+2 saltos" estava errada, direção perigosa (14/09/2026, mesmo
-- dia da seção 15, mesma sessão)
-- ============================================================================================
-- A seção 15 (aplicada mais cedo hoje) trocou becker_dias_uteis(disp,1,abr) por
-- becker_dias_uteis(disp,2,abr), validada contra 3 "prints do tribunal". Essa validação
-- estava errada — mesmo padrão já visto no caso do Recurso de Revista (tribunal pode exibir
-- prazo diferente do real em telas menos autoritativas, tipo "Meus Expedientes" em PDF).
--
-- PROVA (mais forte que print): ela mandou a tela oficial "Expediente(s) do processo" do
-- PJe — a tabela que lista TODAS as intimações do processo com Data de Ciência, Prazo (dias)
-- e Fim do Prazo, calculados pela coluna "Confirmado por: Sistema" (o próprio PJe, não uma
-- interpretação de terceiro). 9 linhas reais do processo 0000840-51.2026.5.12.0030 (Sebastião
-- Marcal de Freitas x Rodalog), destinatários variados (Rodalog e Sebastião), prazos de 5/8/
-- 10/15 dias. Testei a fórmula do sistema contra as 9: **8 de 9 bateram exato usando só 1
-- salto** (ciência = disp + 1 dia útil, +N dias úteis direto — SEM o salto extra pro "início
-- da contagem" que a seção 15 introduziu). A única que não bateu foi uma "Notificação" (não
-- "Intimação"), meio "Domicílio Eletrônico" — tipo de expedição diferente, regra própria, não
-- invalida o padrão.
--
-- Isso também resolveu, de quebra, uma dúvida real: o card do Sebastião (id 5863/6833, disp
-- 01/09) que ela mandou print achando estar "vencendo hoje" — a intimação em questão é dirigida
-- à RÉ (Rodalog), não a nós (confirmado pelo rodapé "Intimado(s)/Citado(s): RODALOG..." em
-- todas as 4 cópias do ato, e pela própria tabela do PJe, que lista essa linha com
-- destinatário Rodalog). Não é prazo nosso, independente da fórmula de data.
--
-- FEITO:
--   1. `becker_dias_uteis(disp,2,abr)` revertido para `becker_dias_uteis(disp,1,abr)` em
--      `trt_gera_prazos` — descrição volta a dizer "+1+N dias úteis".
--   2. 37 prazos com `fonte='DJEN/calculado'` e `+2+` na descrição (`status` estimado ou
--      confirmado) foram deletados pelo id exato e regerados via
--      `trt_gera_prazos('2026-08-25','2026-09-14',true)` — a janela larga também capturou
--      atos que nunca tinham gerado prazo, então o total final ficou maior que 37 (esperado,
--      mesmo padrão de janelas largas já usado nesta sessão).
--   3. `trt_gera_prazos` sempre grava como `status='estimado'` — os 11 que estavam
--      `confirmado` (confirmados em cima da data ERRADA) voltaram pra fila "a conferir" com a
--      data corrigida. Isso é o comportamento certo: a confirmação anterior valeu pra uma data
--      que não existe mais.
--   4. Dos recalculados, 23 ficaram vencidos com a correção (incluindo o id do
--      Sebastião/Rodalog, que sai por ser da parte contrária, e um dos "outros 5" pendentes —
--      Paulo Sergio Zampieri — que fica registrado à parte, sem decidir se é nosso ou não) —
--      excluídos, mesma regra já usada hoje pro N=8→15 e pro feriado TRT-12 ("vencido depois
--      de correção de fórmula não fica, futuro fica pra conferência").
--   5. **ATENÇÃO IMEDIATA**: 2 dos que eram `confirmado` (Adna Paola Batista Breitenbach e
--      Guilherme Hoepers Meneghelli, ambos disp. 02/09, TRT-12) tinham sido confirmados com
--      data 15/09 — a fórmula corrigida mostra que o prazo real é HOJE (14/09). Avisado a ela
--      diretamente no chat, fora deste arquivo.
--
-- Achado separado, NÃO corrigido aqui (fica pra depois): `trt_gera_prazos` não confere se a
-- intimação é dirigida ao nosso cliente (reclamante) ou à parte contrária (reclamado) antes de
-- gerar prazo — só olha se o texto bate com padrões conhecidos. O caso do Sebastião/Rodalog
-- mostra que isso pode gerar prazo nosso por engano quando a ordem é claramente pra outra
-- parte. Precisa de investigação própria (quantos outros prazos abertos hoje têm esse mesmo
-- problema) antes de decidir como resolver.

-- ============================================================================================
-- 23) NOVO: designação de audiência não gera prazo (14/09/2026, mesma sessão)
-- ============================================================================================
-- Ela apontou o card de Adna Paola Batista Breitenbach (0002542-11.2025.5.12.0016, um dos 2
-- que viraram "hoje" na correção da seção 22) — o despacho em questão só designa audiência de
-- instrução (18/02/2027) e traz cláusulas CONDICIONAIS ("em 5 dias, sob pena de preclusão" —
-- só se houver conflito de agenda dos procuradores; "em até 5 dias úteis antes da audiência" —
-- só se for arrolar testemunha; "prazo mínimo de cinco dias" — só se precisar de intérprete
-- de Libras). Nenhuma é ordem incondicional de verdade pra cumprir agora. Confirmado pela
-- própria tela oficial "Expediente(s) do processo" do PJe: essa intimação aparece com
-- **Prazo: 0, Fim do Prazo: --** — o tribunal também não conta isso como prazo.
--
-- O sistema tinha gerado prazo mesmo assim porque o texto cita "em 5 dias" em algum lugar (a
-- cláusula condicional), e isso bateu por coincidência com o n_base=5 padrão (default de
-- qualquer ato trabalhista sem classe de recurso/sentença) — não veio do n_dirigido (o verbo
-- "solicitar" não está na lista de verbos de ordem que a função já reconhece, então n_dirigido
-- ficou null, corretamente).
--
-- Medido: 15 CNJs distintos em `publicacoes_atos` têm esse mesmo padrão ("Designo o dia
-- dd/mm/aaaa... audiência", boilerplate padrão de TRT-12/Joinville com instruções de Zoom) —
-- só 1 tinha prazo aberto gerado (o da Adna Paola, id 6849, removido). Nenhum é classe
-- "Recurso/Agravo". Os outros 14 são históricos, sem prazo gerado atualmente.
--
-- FEITO: `trt_gera_prazos` ganhou um filtro extra — exclui o candidato quando o texto casa
-- "Designo o dia dd/mm/aaaa...audiência/instrução" E `n_dirigido` está null (nenhuma ordem
-- dirigida de verdade foi detectada no mesmo texto). Se um despacho de designação de audiência
-- também trouxer uma ordem substantiva separada (verbo diga/junte/apresente/etc + N dias),
-- n_dirigido não fica null e o prazo continua sendo gerado normalmente — só exclui quando é
-- PURO agendamento.
--
-- CONFERIDO: dry-run não traz mais candidato pro CNJ da Adna Paola em nenhuma janela; prazo
-- id 6849 removido.

-- ADENDO à seção 23 (mesma sessão, minutos depois): em vez de simplesmente excluir o
-- candidato de designação de audiência, ela pediu pra avisar mesmo assim — "bom abrir prazo
-- para ciência" / "colocar algo tipo no prazo, avisar audiência marcada". Trocado: quando
-- `is_audiencia` (designação de audiência sem ordem dirigida), o candidato passa a ser gravado
-- com a DATA DA AUDIÊNCIA (extraída do texto via "Designo o dia dd/mm/aaaa...") em vez de uma
-- contagem de dias úteis, descrição "AUDIÊNCIA MARCADA: dd/mm/aaaa, às HHh" em vez de
-- "ESTIMADO: ... dias úteis", e `fonte='DJEN/audiencia'` (em vez de 'DJEN/calculado') pra não
-- carregar a explicação de fórmula de dias úteis, que não se aplica aqui.
--
-- Isso não gera alarme de urgência (a data é a da audiência, normalmente meses no futuro, não
-- um prazo de poucos dias) — resolve o pedido dela sem inventar tabela nova nem mexer na aba
-- Audiências (que é de outro fluxo, alimentado separadamente pelo Legal Mail).
--
-- Aproveitado pra corrigir 2 textos da UI (site/index.html) que tinham ficado desatualizados
-- da reversão da seção 22 (ainda diziam "+2 dias úteis" hardcoded, da fórmula errada que foi
-- revertida): a linha "Conta:" do modal do prazo (verPrazo) e o tooltip do selo "⚠ ESTIMADO"
-- (ambos agora dizem "+1 dia útil", e a linha "Conta:" só aparece pra fonte='DJEN/calculado' —
-- não faz sentido pra audiência marcada).

-- ============================================================================================
-- 24) FIX: categoria "custas" não confere negação — achado no card do Guilherme Hoepers
-- Meneghelli (0001024-22.2025.5.12.0004, mesma sessão)
-- ============================================================================================
-- Ela estranhou o selo de custas no card do Guilherme e perguntou "você não tem o despacho
-- aí?" — puxei o texto: é a decisão de ADMISSIBILIDADE do Recurso de Revista dele (recorrente,
-- nosso cliente), "OJC de Análise de Recurso", concluindo "Recebo parcialmente o recurso.
-- Publique-se e intime-se." — confirma que o recurso subiu (foi recebido, ao menos em parte)
-- pro TST. Nada de custas a pagar.
--
-- `lm_categoria_prazo(t)` categorizava como 'custas' só com `t ~* 'custas|recolh|preparo|...'`,
-- sem checar negação. O despacho diz literalmente **"Desnecessário o preparo."** — o oposto de
-- custas devida — e mesmo assim bateu na keyword "preparo". Corrigido: agora checa primeiro se
-- a palavra vem negada (desnecessário/dispensado/isento/sem necessidade de + guia/GRU/taxa/
-- custas/recolhimento/preparo) numa janela curta, e só categoriza 'custas' se não for negação.
--
-- Medido: só o prazo do Guilherme (id 6837) tinha esse problema especificamente hoje. Outros
-- `categoria='custas'` existentes não usam a keyword negada — conferido caso a caso, a função
-- nova não muda a categoria deles.
--
-- Achado lateral (mesmo texto, mesmo tipo de bug): a keyword "apresent" (pra categoria
-- 'documentos') também deu falso positivo no mesmo despacho — bateu em "recurso apresentado em
-- 12/08/2026" (constatação de tempestividade, não ordem de apresentar nada). Por isso o prazo
-- 6837 foi corrigido direto pra categoria='geral' (não usando o resultado da função, que ainda
-- erraria pra 'documentos' por esse motivo diferente) — esse segundo bug (keyword "apresent"
-- capturando qualquer uso da palavra, não só ordem de apresentar) fica registrado, não
-- corrigido agora — mexer nele exige mais cuidado (negative lookaheads pra "apresentado"/
-- "apresentação" vs a ordem imperativa "apresente"), fora do escopo desta correção pontual.
--
-- Achado lateral 2 (não corrigido, avisado a ela): o ato do Guilherme tem `classe=null` em
-- `publicacoes_atos` (não foi coletada pra esse tipo de ato "OJC de Análise de Recurso"), então
-- o prazo caiu no N=5 padrão em vez de N=8 (regra Recurso/Agravo) — mesmo sendo, na prática,
-- uma janela pra avaliar Agravo de Instrumento em Recurso de Revista (AIRR) contra os pontos do
-- recurso que não foram admitidos. Lado seguro (avisa 3 dias antes, nunca depois), não
-- corrigido nesta migration — decisão de generalizar por padrão de texto (não só classe) fica
-- pra depois, se ela confirmar que quer.

-- ============================================================================================
-- 25) NOVO: marcação de 1º/2º grau (TRT) nos prazos — texto do despacho, não CNJ (14/09/2026,
-- mesma sessão)
-- ============================================================================================
-- Ela apontou: "você também não está marcando o que é 1º ou 2º grau nos TRT". Existia só
-- `_tribunalCNJ` (site/index.html), usada só na exportação CSV, que deriva grau pelos dígitos
-- do CNJ (órgão julgador '0000' = 2º grau) — regra validada e correta pra TJ (confirmado contra
-- a planilha dela: "...8.24.0000=TJSC 2G, ...8.24.0038=TJSC 1G"), mas ERRADA pra TRT/PJe: nessa
-- Justiça o número do processo NÃO muda entre 1º e 2º grau (mesmo CNJ do início ao fim, inclusive
-- quando sobe pro TST) — confirmado tanto pelas telas "Expediente(s) do processo" dela (abas
-- "1º grau/2º grau/TST" pro MESMO número) quanto testando direto: o CNJ do Guilherme
-- (0001024-22.2025.5.12.0004, órgão '0004'≠'0000') é 2º grau de verdade. Cheguei a implementar
-- e quase publicar uma versão reaproveitando a regra do CNJ pro TRT — testei contra o CNJ do
-- Guilherme ANTES de commitar, deu resposta errada ("1º grau"), revertido sem nada publicado.
--
-- Perguntei a ela se queria usar só `classe` (só ~37% de cobertura, mas 100% seguro) ou também
-- investigar o texto do despacho (mais cobertura, precisa validar) — ela escolheu investigar o
-- texto.
--
-- MEDIDO (`publicacoes_atos`, sem coluna própria de órgão julgador — só texto puro): não dá pra
-- confiar em presença simples da palavra ("vara do trabalho" aparece em 952 atos, "turma" em
-- 156, mas 35 têm as duas — ato de 2º grau que cita "Vara de origem" no corpo). Olhando esses 35
-- casos: atos de 2º grau (classes ROT/RORSum/AP) trazem "Turma" no CABEÇALHO; atos de 1º grau
-- (classe ATOrd) trazem "Xª Vara do Trabalho de [cidade]" direto no cabeçalho, sem "Turma".
--
-- HEURÍSTICA: dentro dos primeiros 400 caracteres do texto (cabeçalho), qual sinal aparece
-- PRIMEIRO — `turma|desembargador|relator[a]?:|minist[ér]o` (2º grau/TST) vs `vara do trabalho|
-- juiz(a) do trabalho` (1º grau). Testada contra o universo completo de atos TRT/TST (1212):
-- 908 marcados "1º grau", 180 "2º grau/TST", 124 "sem sinal claro" (fica sem selo, não força
-- resposta errada) — ~90% de cobertura. Validada contra 2 casos reais conhecidos: CNJ do
-- Sebastião/Rodalog (100% "1º grau", processo nunca saiu da fase de conhecimento) e CNJ do
-- Guilherme (transição exata: "1º grau" até 10/04/2026, "2º grau/TST" a partir de 16/04/2026,
-- incluindo o despacho de 02/09/2026 que ela perguntou sobre — bate com o processo ter subido
-- de verdade pro TST).
--
-- FEITO:
--   1. `trt_gera_prazos` ganhou 2 colunas internas (`_pos2`, `_pos1`, posição do primeiro sinal
--      de cada grau nos 400 primeiros caracteres) e uma 3ª (`grau`, texto '1º grau' / '2º grau/
--      TST' / null) — grau é anexado na `descricao` do prazo (" · GRAU" antes do " — ESTIMADO"/
--      " — AUDIÊNCIA MARCADA"), sem quebrar os regexes existentes que leem `descricao`
--      (`_descPrazoDisplay`, o "Conta:" de `verPrazo`) — nenhum dos dois toca a parte antes do
--      "—".
--   2. Retroativo: os 31 prazos TRT ainda abertos (`cumprido=false`, `fonte` DJEN/calculado ou
--      DJEN/audiencia) tiveram a `descricao` atualizada com o grau também — 28 ganharam grau
--      (inclusive o id 6837, Guilherme, corretamente "2º grau/TST"), 3 ficaram sem sinal claro
--      (descricao não mudou).
--   3. `site/index.html`: selo "⬆ 2º grau/TST" no card (`renderPrazosLista`, só aparece quando
--      detectado — "1º grau" é o padrão, não precisa chamar atenção) e a mesma informação na
--      linha de cabeçalho do modal (`verPrazo`), extraída de `p.descricao` por regex (mesmo
--      padrão já usado ali pra extrair o N de dias úteis).
--
-- CONFERIDO: reprodução exata da medição (908/180/124) e da validação Sebastião/Guilherme antes
-- de tocar a função ao vivo; `node --check` no JS extraído; card e modal exibem o selo
-- corretamente pro id 6837.
--
-- Não corrigido aqui, fica registrado: os ~124 atos "sem sinal claro" (10% do universo) ficam
-- sem grau — comportamento seguro (não afirma nada errado), mas pode valer revisar o padrão de
-- texto deles depois, se aparecer volume relevante.
