-- public.trt_gera_prazos(p_de, p_ate, p_commit) — cria o prazo trabalhista que o tribunal não
-- manda. (aplicado via migrations `trt_gera_prazos` e `trt_gera_prazos_fix_ambiguidade`)
--
-- POR QUE EXISTE: o diário do TRT nunca traz "Data final", e lm_upsert_prazo_por_texto() aborta
-- sem esse campo (`if dfinal is null then return 0`). Resultado: 3.245 intimações do TRT e 0
-- prazos. Ver db/pje_comunica_20260908.sql para o levantamento completo.
--
-- ISTO É O CAMINHO QUE NÃO DEPENDE DE NINGUÉM, NÃO É O IDEAL. A data-limite oficial existe na
-- API do Domicílio Eletrônico da PDPJ (campo `prazo` do ComunicacaoProcessualViewModel), que só
-- falta credencial do CNJ para consumir. Quando ela vier, o certo é trocar a data calculada
-- pela oficial e deixar o cálculo como reserva para o que a PDPJ não cobrir. A troca é simples:
-- o prazo nasce com status 'estimado' e a ato_chave identifica o ato de origem.
--
-- COMO CALCULA:
--   data_prazo = becker_dias_uteis(becker_dias_uteis(disponibilizacao, 1), 5)
--                (disponibilização + 1 dia útil de ciência + 5 dias úteis, sem feriado)
--   Conferido contra a tela "Meus Expedientes" do PJe: 6 de 6 exatas.
--
-- N = 5 SEMPRE. Não se lê o texto. Motivo (medido, não achismo):
--   * 4 dos 6 atos do gabarito não contêm nem a palavra "prazo"; 5 dos 6 não citam número de dia
--     nenhum — e todos tinham prazo real no tribunal. "Só cria se o texto falar de prazo"
--     perderia 4 dos 6, incluindo 3 dos 4 que venciam em 10/09.
--   * Só 29% dos textos citam número de dias, e ele costuma ser de outro (perito, parte
--     contrária, norma citada): de 12 textos lidos à mão, só 2 traziam o nosso prazo.
--   * Erro assimétrico: N menor ANTECIPA a data (seguro); N maior PERDE O PRAZO.
--   Os números achados no texto vão para a descrição como aviso ("texto cita 15 dias — conferir").
--
-- ESCOPO: lê de publicacoes_atos (NUNCA de publicacoes direto, senão volta a duplicar).
--   tribunal ~ '^(TRT|TST)'  -- regex, por causa das grafias duplas TRT-12/TRT12
--   sem 'data final' no texto  -- não invadir o caminho que já funciona nos outros tribunais
--   sem 'pauta de julgamento' nem 'ata de sessão'  -- não são expediente com prazo
--
-- IDEMPOTÊNCIA: coluna prazos.ato_chave (cnj|data|ID do ato) + índice único parcial
--   prazos_ato_chave_uk. Rodar duas vezes não duplica. Também pula se já existe prazo do mesmo
--   processo na mesma data-limite (evita bater com prazo vindo por outro caminho).
--
-- GRAVA: status='estimado', tipo='Prazo', fonte='DJEN/calculado', cumprido=false,
--   categoria via lm_categoria_prazo() (que já existia), alertar_dias=3.
--   Descrição: "CLIENTE · TRT-12 — ESTIMADO: disp. dd/mm +1+5 dias úteis [· texto cita N dias]".
--
-- ARMADILHA DE IMPLEMENTAÇÃO: o parâmetro OUT não pode se chamar `ato_chave` — colide com a
-- coluna dentro do `on conflict (ato_chave)` e o Postgres recusa por ambiguidade. Alias no
-- INSERT não resolve: o conflict_target do ON CONFLICT só aceita nome de coluna sem qualificação.
-- Por isso o OUT se chama `chave_do_ato`.
--
-- USO:
--   select * from trt_gera_prazos('2026-08-20','2026-09-08', false);  -- SIMULA, não grava
--   select * from trt_gera_prazos('2026-08-20','2026-09-08', true);   -- grava
--   -- desfazer:  delete from prazos where fonte='DJEN/calculado';
--
-- PRIMEIRA RODADA (08/09/2026): 71 prazos, 57 com processo vinculado, 14 sem.
--   37 em aberto, 34 já vencidos (28/08 a 04/09).
--   Os 34 vencidos foram MANTIDOS de propósito: prazo que expirou antes de o sistema saber dele
--   é justamente o caso de prazo possivelmente perdido, que é o que este trabalho existe para
--   revelar. Não são ruído — precisam ser conferidos um a um.
--   Nenhum outro status de prazo se moveu (conferido antes/depois): só estimado, +71.
--
-- FECHAMENTO AUTOMÁTICO (corrigido em 09/09/2026):
-- O prazo nasce com `legalmail_id` do aviso do Legal Mail que cobre o MESMO ato, porque
-- lm_reconcile() — quem fecha prazo quando o tribunal informa cumprido/excedido — casa por
-- legalmail_id e não por ato_chave. Os 71 primeiros nasceram sem esse vínculo e ficariam
-- abertos para sempre mesmo depois de cumpridos; foram ligados na mão e a função corrigida.
-- A view publicacoes_atos expõe `legalmail_id_do_ato` (qualquer cópia do grupo serve: o status
-- vem do tribunal e é igual para todas). O vínculo só é gravado se nenhum outro prazo já usar
-- aquele id, porque uq_prazos_legalmail é único.
--
-- LIMITE CONHECIDO, medido em 09/09/2026: para o TRT o Legal Mail NÃO reporta prazo_status.
-- Rodada completa de reconciliação (5.449 avisos) fechou 15 prazos de outros tribunais
-- (12 cumpridos, 3 excedidos) e ZERO dos 71 do TRT. É a mesma causa raiz: sem "Data final" o
-- Legal Mail nunca registrou prazo para o TRT, então não tem status para informar.
-- Quem fecha prazo trabalhista, então:
--   1. Export "Meus Expedientes" do PJe: o que NÃO está na lista já foi cumprido. Autoritativo
--      e grátis, mas manual.
--   2. Domicílio Eletrônico da PDPJ: campos ciente, dataCiente, emCurso, status. Precisa de
--      credencial do CNJ (ver db/pje_comunica_20260908.sql).
--   3. MNI-REST consultar-avisos-pendentes: DESCARTADO em 09/09/2026, depois de testar.
--      A ideia era boa (a lista de avisos pendentes é o inverso do que fechou, e o corpo do
--      pedido leva usuario/senha DO TRIBUNAL, não do CNJ), mas não se chega lá:
--        - via gateway da PDPJ: 401 com WWW-Authenticate: Bearer realm="Unknown" — o gateway
--          exige token OAuth2 do CNJ ANTES de olhar o usuario/senha do corpo. Mesmo bloqueio
--          do caminho 2, então não é alternativa a ele.
--        - em produção o mni-rest responde 500 "GENERAL" (o registro do Eureka que eu li é de
--          homologação; não parece publicado em produção).
--        - direto no tribunal (pje.trt12.jus.br/.../intercomunicacao): 403 do CloudFront em
--          TUDO, inclusive na home. É bloqueio de tráfego de datacenter, não da API: o
--          www.trt12.jus.br (outra infra) responde 200 normalmente. Ou seja, integração
--          servidor-a-servidor não alcança o PJe do TRT12 de forma alguma.
--      Não se tenta contornar o bloqueio deles.
-- NÃO usar "houve movimento posterior no processo" para fechar: em 09/09 isso valia para 10 dos
-- 39 vencidos, e é indício, não prova de cumprimento. Fechar prazo por indício é pior do que
-- deixar aberto.
--
-- AGENDADO em cron.job (nada disso rodava antes — ver db/djen_supabase_pgcron.sql):
--   trt_prazos_diario  '20 10 * * *'  select trt_gera_prazos(current_date-15, current_date, true)
